/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type MainLoginBody,
    MainLoginBodyFromJSON,
    MainLoginBodyToJSON,
} from '../models/MainLoginBody';
import {
    type MainLoginResponse,
    MainLoginResponseFromJSON,
    MainLoginResponseToJSON,
} from '../models/MainLoginResponse';

export interface V1LevelupApiLogInPostRequest {
    body: MainLoginBody;
}

export interface V1LevelupApiSignUpPostRequest {
    body: MainLoginBody;
}

/**
 * 
 */
export class LoginApi extends runtime.BaseAPI {

    /**
     * Creates request options for v1LevelupApiLogInPost without sending the request
     */
    async v1LevelupApiLogInPostRequestOpts(requestParameters: V1LevelupApiLogInPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling v1LevelupApiLogInPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/levelup_api/logIn`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MainLoginBodyToJSON(requestParameters['body']),
        };
    }

    /**
     * take the email and the password, hash the password, check for user and login
     * Log In the user
     */
    async v1LevelupApiLogInPostRaw(requestParameters: V1LevelupApiLogInPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainLoginResponse>> {
        const requestOptions = await this.v1LevelupApiLogInPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainLoginResponseFromJSON(jsonValue));
    }

    /**
     * take the email and the password, hash the password, check for user and login
     * Log In the user
     */
    async v1LevelupApiLogInPost(requestParameters: V1LevelupApiLogInPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainLoginResponse> {
        const response = await this.v1LevelupApiLogInPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1LevelupApiSignUpPost without sending the request
     */
    async v1LevelupApiSignUpPostRequestOpts(requestParameters: V1LevelupApiSignUpPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling v1LevelupApiSignUpPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/levelup_api/signUp`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MainLoginBodyToJSON(requestParameters['body']),
        };
    }

    /**
     * take the email and the password, hash the password, create the user and make cookies
     * Sign up the user
     */
    async v1LevelupApiSignUpPostRaw(requestParameters: V1LevelupApiSignUpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainLoginResponse>> {
        const requestOptions = await this.v1LevelupApiSignUpPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainLoginResponseFromJSON(jsonValue));
    }

    /**
     * take the email and the password, hash the password, create the user and make cookies
     * Sign up the user
     */
    async v1LevelupApiSignUpPost(requestParameters: V1LevelupApiSignUpPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainLoginResponse> {
        const response = await this.v1LevelupApiSignUpPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
