/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type MainLoginResponse,
    MainLoginResponseFromJSON,
    MainLoginResponseToJSON,
} from '../models/MainLoginResponse';
import {
    type MainProfileCreationBody,
    MainProfileCreationBodyFromJSON,
    MainProfileCreationBodyToJSON,
} from '../models/MainProfileCreationBody';
import {
    type MainUpdateUserBody,
    MainUpdateUserBodyFromJSON,
    MainUpdateUserBodyToJSON,
} from '../models/MainUpdateUserBody';
import {
    type MainUserResponse,
    MainUserResponseFromJSON,
    MainUserResponseToJSON,
} from '../models/MainUserResponse';

export interface V1LevelupApiCreateProfilePostRequest {
    body: MainProfileCreationBody;
}

export interface V1LevelupApiUpdateUserPostRequest {
    body: MainUpdateUserBody;
}

/**
 * 
 */
export class PlayerApi extends runtime.BaseAPI {

    /**
     * Creates request options for v1LevelupApiCreateProfilePost without sending the request
     */
    async v1LevelupApiCreateProfilePostRequestOpts(requestParameters: V1LevelupApiCreateProfilePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling v1LevelupApiCreateProfilePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/levelup_api/createProfile`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MainProfileCreationBodyToJSON(requestParameters['body']),
        };
    }

    /**
     * Create the player with user\'s info, skills and quests
     * Create the player
     */
    async v1LevelupApiCreateProfilePostRaw(requestParameters: V1LevelupApiCreateProfilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainLoginResponse>> {
        const requestOptions = await this.v1LevelupApiCreateProfilePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainLoginResponseFromJSON(jsonValue));
    }

    /**
     * Create the player with user\'s info, skills and quests
     * Create the player
     */
    async v1LevelupApiCreateProfilePost(requestParameters: V1LevelupApiCreateProfilePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainLoginResponse> {
        const response = await this.v1LevelupApiCreateProfilePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1LevelupApiUpdateUserPost without sending the request
     */
    async v1LevelupApiUpdateUserPostRequestOpts(requestParameters: V1LevelupApiUpdateUserPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling v1LevelupApiUpdateUserPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/levelup_api/updateUser`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MainUpdateUserBodyToJSON(requestParameters['body']),
        };
    }

    /**
     * Update the player
     * Update the player
     */
    async v1LevelupApiUpdateUserPostRaw(requestParameters: V1LevelupApiUpdateUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.v1LevelupApiUpdateUserPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update the player
     * Update the player
     */
    async v1LevelupApiUpdateUserPost(requestParameters: V1LevelupApiUpdateUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1LevelupApiUpdateUserPostRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for v1LevelupApiUserProfileGet without sending the request
     */
    async v1LevelupApiUserProfileGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/levelup_api/userProfile`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get everything about the player
     * Get the player
     */
    async v1LevelupApiUserProfileGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainUserResponse>> {
        const requestOptions = await this.v1LevelupApiUserProfileGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainUserResponseFromJSON(jsonValue));
    }

    /**
     * Get everything about the player
     * Get the player
     */
    async v1LevelupApiUserProfileGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainUserResponse> {
        const response = await this.v1LevelupApiUserProfileGetRaw(initOverrides);
        return await response.value();
    }

}
