/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type MainQuestsReponse,
    MainQuestsReponseFromJSON,
    MainQuestsReponseToJSON,
} from '../models/MainQuestsReponse';

/**
 * 
 */
export class QuestsApi extends runtime.BaseAPI {

    /**
     * Creates request options for v1LevelupApiQuestsGet without sending the request
     */
    async v1LevelupApiQuestsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/levelup_api/quests`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all quests for the user
     */
    async v1LevelupApiQuestsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainQuestsReponse>> {
        const requestOptions = await this.v1LevelupApiQuestsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainQuestsReponseFromJSON(jsonValue));
    }

    /**
     * Get all quests for the user
     */
    async v1LevelupApiQuestsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainQuestsReponse> {
        const response = await this.v1LevelupApiQuestsGetRaw(initOverrides);
        return await response.value();
    }

}
