/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type MainQuestCompletionResponse,
    MainQuestCompletionResponseFromJSON,
    MainQuestCompletionResponseToJSON,
} from '../models/MainQuestCompletionResponse';
import {
    type MainQuestCreationPayload,
    MainQuestCreationPayloadFromJSON,
    MainQuestCreationPayloadToJSON,
} from '../models/MainQuestCreationPayload';
import {
    type MainQuestsReponse,
    MainQuestsReponseFromJSON,
    MainQuestsReponseToJSON,
} from '../models/MainQuestsReponse';

export interface V1LevelupApiUserQuestCreationPostRequest {
    body: MainQuestCreationPayload;
}

export interface V1LevelupApiUserQuestIdCompletePostRequest {
    id: number;
}

export interface V1LevelupApiUserQuestIdCompleteSubquestPostRequest {
    id: number;
}

export interface V1LevelupApiUserQuestIdDeleteDeleteRequest {
    id: number;
}

export interface V1LevelupApiUserQuestIdDeleteSubquestDeleteRequest {
    id: number;
}

/**
 * 
 */
export class QuestsApi extends runtime.BaseAPI {

    /**
     * Creates request options for v1LevelupApiQuestsGet without sending the request
     */
    async v1LevelupApiQuestsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/levelup_api/quests`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all quests for the user
     */
    async v1LevelupApiQuestsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainQuestsReponse>> {
        const requestOptions = await this.v1LevelupApiQuestsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainQuestsReponseFromJSON(jsonValue));
    }

    /**
     * Get all quests for the user
     */
    async v1LevelupApiQuestsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainQuestsReponse> {
        const response = await this.v1LevelupApiQuestsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1LevelupApiUserQuestCreationPost without sending the request
     */
    async v1LevelupApiUserQuestCreationPostRequestOpts(requestParameters: V1LevelupApiUserQuestCreationPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling v1LevelupApiUserQuestCreationPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/levelup_api/user/quest-creation`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MainQuestCreationPayloadToJSON(requestParameters['body']),
        };
    }

    /**
     * Get all quests for the user
     */
    async v1LevelupApiUserQuestCreationPostRaw(requestParameters: V1LevelupApiUserQuestCreationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.v1LevelupApiUserQuestCreationPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get all quests for the user
     */
    async v1LevelupApiUserQuestCreationPost(requestParameters: V1LevelupApiUserQuestCreationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1LevelupApiUserQuestCreationPostRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for v1LevelupApiUserQuestIdCompletePost without sending the request
     */
    async v1LevelupApiUserQuestIdCompletePostRequestOpts(requestParameters: V1LevelupApiUserQuestIdCompletePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling v1LevelupApiUserQuestIdCompletePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/levelup_api/user/quest/{id}/complete`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Complete a sub-quest
     */
    async v1LevelupApiUserQuestIdCompletePostRaw(requestParameters: V1LevelupApiUserQuestIdCompletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainQuestCompletionResponse>> {
        const requestOptions = await this.v1LevelupApiUserQuestIdCompletePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainQuestCompletionResponseFromJSON(jsonValue));
    }

    /**
     * Complete a sub-quest
     */
    async v1LevelupApiUserQuestIdCompletePost(requestParameters: V1LevelupApiUserQuestIdCompletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainQuestCompletionResponse> {
        const response = await this.v1LevelupApiUserQuestIdCompletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1LevelupApiUserQuestIdCompleteSubquestPost without sending the request
     */
    async v1LevelupApiUserQuestIdCompleteSubquestPostRequestOpts(requestParameters: V1LevelupApiUserQuestIdCompleteSubquestPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling v1LevelupApiUserQuestIdCompleteSubquestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/levelup_api/user/quest/{id}/complete-subquest`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Complete a sub-quest
     */
    async v1LevelupApiUserQuestIdCompleteSubquestPostRaw(requestParameters: V1LevelupApiUserQuestIdCompleteSubquestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainQuestCompletionResponse>> {
        const requestOptions = await this.v1LevelupApiUserQuestIdCompleteSubquestPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainQuestCompletionResponseFromJSON(jsonValue));
    }

    /**
     * Complete a sub-quest
     */
    async v1LevelupApiUserQuestIdCompleteSubquestPost(requestParameters: V1LevelupApiUserQuestIdCompleteSubquestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainQuestCompletionResponse> {
        const response = await this.v1LevelupApiUserQuestIdCompleteSubquestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1LevelupApiUserQuestIdDeleteDelete without sending the request
     */
    async v1LevelupApiUserQuestIdDeleteDeleteRequestOpts(requestParameters: V1LevelupApiUserQuestIdDeleteDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling v1LevelupApiUserQuestIdDeleteDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/levelup_api/user/quest/{id}/delete`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Complete a sub-quest
     */
    async v1LevelupApiUserQuestIdDeleteDeleteRaw(requestParameters: V1LevelupApiUserQuestIdDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.v1LevelupApiUserQuestIdDeleteDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Complete a sub-quest
     */
    async v1LevelupApiUserQuestIdDeleteDelete(requestParameters: V1LevelupApiUserQuestIdDeleteDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1LevelupApiUserQuestIdDeleteDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for v1LevelupApiUserQuestIdDeleteSubquestDelete without sending the request
     */
    async v1LevelupApiUserQuestIdDeleteSubquestDeleteRequestOpts(requestParameters: V1LevelupApiUserQuestIdDeleteSubquestDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling v1LevelupApiUserQuestIdDeleteSubquestDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/levelup_api/user/quest/{id}/delete-subquest`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a sub-quest
     */
    async v1LevelupApiUserQuestIdDeleteSubquestDeleteRaw(requestParameters: V1LevelupApiUserQuestIdDeleteSubquestDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.v1LevelupApiUserQuestIdDeleteSubquestDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a sub-quest
     */
    async v1LevelupApiUserQuestIdDeleteSubquestDelete(requestParameters: V1LevelupApiUserQuestIdDeleteSubquestDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1LevelupApiUserQuestIdDeleteSubquestDeleteRaw(requestParameters, initOverrides);
    }

}
