/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MainSkillsResponse,
} from '../models/index';
import {
    MainSkillsResponseFromJSON,
    MainSkillsResponseToJSON,
} from '../models/index';

export interface V1LevelupApiSkillsGetRequest {
    name?: string;
}

/**
 * 
 */
export class SkillsApi extends runtime.BaseAPI {

    /**
     * get skills, limited to 200 results
     * Get skills from database
     */
    async v1LevelupApiSkillsGetRaw(requestParameters: V1LevelupApiSkillsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainSkillsResponse>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/levelup_api/skills`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainSkillsResponseFromJSON(jsonValue));
    }

    /**
     * get skills, limited to 200 results
     * Get skills from database
     */
    async v1LevelupApiSkillsGet(requestParameters: V1LevelupApiSkillsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainSkillsResponse> {
        const response = await this.v1LevelupApiSkillsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
