/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type MainSkillCreationPayload,
    MainSkillCreationPayloadFromJSON,
    MainSkillCreationPayloadToJSON,
} from '../models/MainSkillCreationPayload';
import {
    type MainSkillsExcludeResponse,
    MainSkillsExcludeResponseFromJSON,
    MainSkillsExcludeResponseToJSON,
} from '../models/MainSkillsExcludeResponse';
import {
    type MainSkillsNotOwnedResponse,
    MainSkillsNotOwnedResponseFromJSON,
    MainSkillsNotOwnedResponseToJSON,
} from '../models/MainSkillsNotOwnedResponse';
import {
    type MainSkillsResponse,
    MainSkillsResponseFromJSON,
    MainSkillsResponseToJSON,
} from '../models/MainSkillsResponse';
import {
    type MainUsersSkillsResponse,
    MainUsersSkillsResponseFromJSON,
    MainUsersSkillsResponseToJSON,
} from '../models/MainUsersSkillsResponse';

export interface V1LevelupApiCreateSkillPostRequest {
    body: MainSkillCreationPayload;
}

export interface V1LevelupApiSkillIdDeactivateDeleteRequest {
    id: number;
}

export interface V1LevelupApiSkillsGetRequest {
    name?: string;
}

export interface V1LevelupApiSkillsNotUserGetRequest {
    name?: string;
}

export interface V1LevelupApiUserSkillsExcludeGetRequest {
    name?: string;
    excludeIds?: Array<number>;
    excludeName?: string;
}

/**
 * 
 */
export class SkillsApi extends runtime.BaseAPI {

    /**
     * Creates request options for v1LevelupApiCreateSkillPost without sending the request
     */
    async v1LevelupApiCreateSkillPostRequestOpts(requestParameters: V1LevelupApiCreateSkillPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['body'] == null) {
            throw new runtime.RequiredError(
                'body',
                'Required parameter "body" was null or undefined when calling v1LevelupApiCreateSkillPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/levelup_api/create-skill`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MainSkillCreationPayloadToJSON(requestParameters['body']),
        };
    }

    /**
     * create skill for user
     * Create skill
     */
    async v1LevelupApiCreateSkillPostRaw(requestParameters: V1LevelupApiCreateSkillPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.v1LevelupApiCreateSkillPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * create skill for user
     * Create skill
     */
    async v1LevelupApiCreateSkillPost(requestParameters: V1LevelupApiCreateSkillPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1LevelupApiCreateSkillPostRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for v1LevelupApiSkillIdDeactivateDelete without sending the request
     */
    async v1LevelupApiSkillIdDeactivateDeleteRequestOpts(requestParameters: V1LevelupApiSkillIdDeactivateDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling v1LevelupApiSkillIdDeactivateDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/levelup_api/skill/{id}/deactivate`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * deactivate the skill
     * Deactivate
     */
    async v1LevelupApiSkillIdDeactivateDeleteRaw(requestParameters: V1LevelupApiSkillIdDeactivateDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.v1LevelupApiSkillIdDeactivateDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * deactivate the skill
     * Deactivate
     */
    async v1LevelupApiSkillIdDeactivateDelete(requestParameters: V1LevelupApiSkillIdDeactivateDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.v1LevelupApiSkillIdDeactivateDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for v1LevelupApiSkillsGet without sending the request
     */
    async v1LevelupApiSkillsGetRequestOpts(requestParameters: V1LevelupApiSkillsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/levelup_api/skills`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get skills, limited to 200 results
     * Get skills from database
     */
    async v1LevelupApiSkillsGetRaw(requestParameters: V1LevelupApiSkillsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainSkillsResponse>> {
        const requestOptions = await this.v1LevelupApiSkillsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainSkillsResponseFromJSON(jsonValue));
    }

    /**
     * get skills, limited to 200 results
     * Get skills from database
     */
    async v1LevelupApiSkillsGet(requestParameters: V1LevelupApiSkillsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainSkillsResponse> {
        const response = await this.v1LevelupApiSkillsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1LevelupApiSkillsNotUserGet without sending the request
     */
    async v1LevelupApiSkillsNotUserGetRequestOpts(requestParameters: V1LevelupApiSkillsNotUserGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/levelup_api/skills-not-user`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get skills not owned by the user, limited to 200 results
     * Get skills from database
     */
    async v1LevelupApiSkillsNotUserGetRaw(requestParameters: V1LevelupApiSkillsNotUserGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainSkillsNotOwnedResponse>> {
        const requestOptions = await this.v1LevelupApiSkillsNotUserGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainSkillsNotOwnedResponseFromJSON(jsonValue));
    }

    /**
     * get skills not owned by the user, limited to 200 results
     * Get skills from database
     */
    async v1LevelupApiSkillsNotUserGet(requestParameters: V1LevelupApiSkillsNotUserGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainSkillsNotOwnedResponse> {
        const response = await this.v1LevelupApiSkillsNotUserGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1LevelupApiUserSkillsExcludeGet without sending the request
     */
    async v1LevelupApiUserSkillsExcludeGetRequestOpts(requestParameters: V1LevelupApiUserSkillsExcludeGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        if (requestParameters['excludeIds'] != null) {
            queryParameters['exclude_ids'] = requestParameters['excludeIds']!.join(runtime.COLLECTION_FORMATS["csv"]);
        }

        if (requestParameters['excludeName'] != null) {
            queryParameters['excludeName'] = requestParameters['excludeName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/levelup_api/user/skills_exclude`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get user\'s skills
     * Get user\'s skills from database
     */
    async v1LevelupApiUserSkillsExcludeGetRaw(requestParameters: V1LevelupApiUserSkillsExcludeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainSkillsExcludeResponse>> {
        const requestOptions = await this.v1LevelupApiUserSkillsExcludeGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainSkillsExcludeResponseFromJSON(jsonValue));
    }

    /**
     * get user\'s skills
     * Get user\'s skills from database
     */
    async v1LevelupApiUserSkillsExcludeGet(requestParameters: V1LevelupApiUserSkillsExcludeGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainSkillsExcludeResponse> {
        const response = await this.v1LevelupApiUserSkillsExcludeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for v1LevelupApiUserSkillsGet without sending the request
     */
    async v1LevelupApiUserSkillsGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/levelup_api/user/skills`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get user\'s skills
     * Get user\'s skills from database
     */
    async v1LevelupApiUserSkillsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainUsersSkillsResponse>> {
        const requestOptions = await this.v1LevelupApiUserSkillsGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainUsersSkillsResponseFromJSON(jsonValue));
    }

    /**
     * get user\'s skills
     * Get user\'s skills from database
     */
    async v1LevelupApiUserSkillsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainUsersSkillsResponse> {
        const response = await this.v1LevelupApiUserSkillsGetRaw(initOverrides);
        return await response.value();
    }

}
