/* tslint:disable */
/* eslint-disable */
/**
 * Your API Title
 * This is a sample API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MainTestResponse,
} from '../models/index';
import {
    MainTestResponseFromJSON,
    MainTestResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class TestTagApi extends runtime.BaseAPI {

    /**
     * test job
     * testing swagger and api
     */
    async testGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainTestResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/test`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainTestResponseFromJSON(jsonValue));
    }

    /**
     * test job
     * testing swagger and api
     */
    async testGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainTestResponse> {
        const response = await this.testGetRaw(initOverrides);
        return await response.value();
    }

}
