/* tslint:disable */
/* eslint-disable */
/**
 * Your API Title
 * This is a sample API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MainTestResponseTwo,
} from '../models/index';
import {
    MainTestResponseTwoFromJSON,
    MainTestResponseTwoToJSON,
} from '../models/index';

/**
 * 
 */
export class TestTag2Api extends runtime.BaseAPI {

    /**
     * test job
     * testing swagger and api
     */
    async testTwoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MainTestResponseTwo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/test-two`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MainTestResponseTwoFromJSON(jsonValue));
    }

    /**
     * test job
     * testing swagger and api
     */
    async testTwoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MainTestResponseTwo> {
        const response = await this.testTwoGetRaw(initOverrides);
        return await response.value();
    }

}
