-- +goose up
CREATE TABLE users(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  firstName TEXT NOT NULL,
  lastName TEXT NOT NULL,
  nickname TEXT NOT NULL,
  dateOfBirth DATE,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  hot_streak NUMBER,
  quests_completed NUMBER,
  repeating_completed NUMBER,
  customs_completed NUMBER,
  experience NUMBER,
  experience_needed NUMBER,
  level NUMBER
);

-- +goose down
DROP TABLE users;
