-- +goose up
CREATE TABLE users(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  firstName TEXT NOT NULL,
  lastName TEXT NOT NULL,
  nickname TEXT NOT NULL,
  dateOfBirth DATE
);

-- +goose down
DROP TABLE users;
