-- +goose up
CREATE TABLE skills(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  name TEXT NOT NULL UNIQUE,
  experience INTEGER,
  experience_needed INTEGER,
  level INTEGER
);

-- +goose down
DROP TABLE skills;
