-- +goose up
CREATE TABLE quests(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  name TEXT NOT NULL UNIQUE,
  experience INTEGER,
  experience_needed INTEGER,
  level INTEGER,
  start_date DATE,
  end_date DATE,
  completed BOOL,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  parent_quest_id BIGINT REFERENCES quests(id) ON DELETE CASCADE
);

-- +goose down
DROP TABLE quests;
