-- +goose up
CREATE TABLE quests(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  name TEXT NOT NULL UNIQUE,
  experience NUMBER,
  experience_needed NUMBER,
  level NUMBER,
  start_date DATE,
  end_date DATE,
  parent_quest_id BIGINT REFERENCES quests(id) ON DELETE CASCADE
);

-- +goose down
DROP TABLE quests;
