-- +goose up
CREATE TABLE quests(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  name TEXT NOT NULL UNIQUE,
  experience NUMBER,
  experience_needed NUMBER,
  level NUMBER
);

-- +goose down
DROP TABLE quests;
