// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Quest struct {
	ID               int64            `json:"id"`
	CreatedAt        time.Time        `json:"created_at"`
	UpdatedAt        time.Time        `json:"updated_at"`
	Name             string           `json:"name"`
	Experience       pgtype.Int4      `json:"experience"`
	ExperienceNeeded pgtype.Int4      `json:"experience_needed"`
	Level            pgtype.Int4      `json:"level"`
	StartDate        pgtype.Date      `json:"start_date"`
	EndDate          pgtype.Date      `json:"end_date"`
	Completed        pgtype.Bool      `json:"completed"`
	UserID           uuid.UUID        `json:"user_id"`
	ParentQuestID    pgtype.Int8      `json:"parent_quest_id"`
	CompletedAt      pgtype.Timestamp `json:"completed_at"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
	Type             pgtype.Text      `json:"type"`
	Failed           pgtype.Bool      `json:"failed"`
	FailedAt         pgtype.Timestamp `json:"failed_at"`
}

type QuestsSkill struct {
	QuestID   int64     `json:"quest_id"`
	UserID    uuid.UUID `json:"user_id"`
	SkillID   int32     `json:"skill_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RefreshToken struct {
	Token     string           `json:"token"`
	CreatedAt time.Time        `json:"created_at"`
	UpdatedAt time.Time        `json:"updated_at"`
	UserID    uuid.UUID        `json:"user_id"`
	ExpiresAt time.Time        `json:"expires_at"`
	RevokedAt pgtype.Timestamp `json:"revoked_at"`
}

type Skill struct {
	ID        int32     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string    `json:"name"`
}

type User struct {
	ID                 uuid.UUID   `json:"id"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
	Firstname          pgtype.Text `json:"firstname"`
	Lastname           pgtype.Text `json:"lastname"`
	Nickname           pgtype.Text `json:"nickname"`
	Bio                pgtype.Text `json:"bio"`
	Dateofbirth        pgtype.Date `json:"dateofbirth"`
	Email              string      `json:"email"`
	Password           string      `json:"password"`
	HotStreak          pgtype.Int4 `json:"hot_streak"`
	QuestsCompleted    pgtype.Int4 `json:"quests_completed"`
	RepeatingCompleted pgtype.Int4 `json:"repeating_completed"`
	CustomsCompleted   pgtype.Int4 `json:"customs_completed"`
	Experience         pgtype.Int4 `json:"experience"`
	ExperienceNeeded   pgtype.Int4 `json:"experience_needed"`
	Level              pgtype.Int4 `json:"level"`
	Money              pgtype.Int8 `json:"money"`
}

type UsersSkill struct {
	UserID           uuid.UUID        `json:"user_id"`
	SkillID          int32            `json:"skill_id"`
	Name             string           `json:"name"`
	CreatedAt        time.Time        `json:"created_at"`
	UpdatedAt        time.Time        `json:"updated_at"`
	Experience       int32            `json:"experience"`
	ExperienceNeeded int32            `json:"experience_needed"`
	Level            int32            `json:"level"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
	DeletedReason    pgtype.Text      `json:"deleted_reason"`
	LeveledAt        pgtype.Timestamp `json:"leveled_at"`
}

type UsersSkillsLink struct {
	UserID        uuid.UUID        `json:"user_id"`
	ParentSkillID int32            `json:"parent_skill_id"`
	ChildSkillID  int32            `json:"child_skill_id"`
	CreatedAt     time.Time        `json:"created_at"`
	UpdatedAt     time.Time        `json:"updated_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
	DeletedReason pgtype.Text      `json:"deleted_reason"`
}

type UsersStat struct {
	UserID                   uuid.UUID `json:"user_id"`
	QuestsCompleted          int32     `json:"quests_completed"`
	RepeatingQuestsCompleted int32     `json:"repeating_quests_completed"`
	CustomQuestsCompleted    int32     `json:"custom_quests_completed"`
	QuestExperienceGained    int32     `json:"quest_experience_gained"`
	SkillExperienceGained    int32     `json:"skill_experience_gained"`
	UpdatedAt                time.Time `json:"updated_at"`
}
