// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quests.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeQuest = `-- name: CompleteQuest :one
UPDATE quests SET updated_at = NOW(), completed = TRUE, completed_at = NOW() WHERE id = $1 AND user_id = $2 RETURNING experience
`

type CompleteQuestParams struct {
	ID     int64     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CompleteQuest(ctx context.Context, arg CompleteQuestParams) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, completeQuest, arg.ID, arg.UserID)
	var experience pgtype.Int4
	err := row.Scan(&experience)
	return experience, err
}

const createQuest = `-- name: CreateQuest :one
INSERT INTO quests(created_at, updated_at, name, experience, user_id, type, start_date, end_date) VALUES (NOW(), NOW(), $1, $2, $3, $4, $5, $6) RETURNING id
`

type CreateQuestParams struct {
	Name       string      `json:"name"`
	Experience pgtype.Int4 `json:"experience"`
	UserID     uuid.UUID   `json:"user_id"`
	Type       pgtype.Text `json:"type"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateQuest(ctx context.Context, arg CreateQuestParams) (int64, error) {
	row := q.db.QueryRow(ctx, createQuest,
		arg.Name,
		arg.Experience,
		arg.UserID,
		arg.Type,
		arg.StartDate,
		arg.EndDate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createQuestSkills = `-- name: CreateQuestSkills :exec
INSERT INTO quests_skills(quest_id, user_id, skill_id, created_at, updated_at) VALUES ($1, $2, $3, NOW(), NOW())
`

type CreateQuestSkillsParams struct {
	QuestID int64     `json:"quest_id"`
	UserID  uuid.UUID `json:"user_id"`
	SkillID int32     `json:"skill_id"`
}

func (q *Queries) CreateQuestSkills(ctx context.Context, arg CreateQuestSkillsParams) error {
	_, err := q.db.Exec(ctx, createQuestSkills, arg.QuestID, arg.UserID, arg.SkillID)
	return err
}

const createSubQuest = `-- name: CreateSubQuest :exec
INSERT INTO quests(created_at, updated_at, name, experience, user_id, parent_quest_id) VALUES (NOW(), NOW(), $1, $2, $3, $4)
`

type CreateSubQuestParams struct {
	Name          string      `json:"name"`
	Experience    pgtype.Int4 `json:"experience"`
	UserID        uuid.UUID   `json:"user_id"`
	ParentQuestID pgtype.Int8 `json:"parent_quest_id"`
}

func (q *Queries) CreateSubQuest(ctx context.Context, arg CreateSubQuestParams) error {
	_, err := q.db.Exec(ctx, createSubQuest,
		arg.Name,
		arg.Experience,
		arg.UserID,
		arg.ParentQuestID,
	)
	return err
}

const deleteQuest = `-- name: DeleteQuest :exec
UPDATE quests SET updated_at = NOW(), deleted_at = NOW(), failed = TRUE, failed_at = NOW() WHERE id = $1 AND user_id = $2
`

type DeleteQuestParams struct {
	ID     int64     `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteQuest(ctx context.Context, arg DeleteQuestParams) error {
	_, err := q.db.Exec(ctx, deleteQuest, arg.ID, arg.UserID)
	return err
}

const deleteQuestSkills = `-- name: DeleteQuestSkills :exec
DELETE FROM quests_skills WHERE user_id = $1 AND quest_id = $2
`

type DeleteQuestSkillsParams struct {
	UserID  uuid.UUID `json:"user_id"`
	QuestID int64     `json:"quest_id"`
}

func (q *Queries) DeleteQuestSkills(ctx context.Context, arg DeleteQuestSkillsParams) error {
	_, err := q.db.Exec(ctx, deleteQuestSkills, arg.UserID, arg.QuestID)
	return err
}

const deleteSubQuest = `-- name: DeleteSubQuest :exec
DELETE FROM quests WHERE user_id = $1 AND id = $2
`

type DeleteSubQuestParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     int64     `json:"id"`
}

func (q *Queries) DeleteSubQuest(ctx context.Context, arg DeleteSubQuestParams) error {
	_, err := q.db.Exec(ctx, deleteSubQuest, arg.UserID, arg.ID)
	return err
}

const getCompletedQuestStats = `-- name: GetCompletedQuestStats :one
SELECT
  COUNT(*) FILTER (WHERE completed = TRUE AND parent_quest_id IS NULL) AS all_completed,
  COUNT(*) FILTER (WHERE completed = TRUE AND type = 'custom') AS custom_completed,
  COUNT(*) FILTER (WHERE completed = TRUE AND type != 'custom') AS repeating_completed,
  COUNT(*) FILTER (WHERE completed = TRUE AND parent_quest_id IS NOT NULL) AS sub_quests_completed
FROM quests
WHERE user_id = $1
  AND deleted_at IS NULL
`

type GetCompletedQuestStatsRow struct {
	AllCompleted       int64 `json:"all_completed"`
	CustomCompleted    int64 `json:"custom_completed"`
	RepeatingCompleted int64 `json:"repeating_completed"`
	SubQuestsCompleted int64 `json:"sub_quests_completed"`
}

func (q *Queries) GetCompletedQuestStats(ctx context.Context, userID uuid.UUID) (GetCompletedQuestStatsRow, error) {
	row := q.db.QueryRow(ctx, getCompletedQuestStats, userID)
	var i GetCompletedQuestStatsRow
	err := row.Scan(
		&i.AllCompleted,
		&i.CustomCompleted,
		&i.RepeatingCompleted,
		&i.SubQuestsCompleted,
	)
	return i, err
}

const getQuestSkills = `-- name: GetQuestSkills :many
SELECT
  us.skill_id,
  us.name
FROM quests_skills qs
JOIN users_skills us
  ON us.user_id = qs.user_id
  AND us.skill_id = qs.skill_id
WHERE qs.quest_id = $2
  AND qs.user_id = $1
  AND us.deleted_at IS NULL
ORDER BY us.name ASC
`

type GetQuestSkillsParams struct {
	UserID  uuid.UUID `json:"user_id"`
	QuestID int64     `json:"quest_id"`
}

type GetQuestSkillsRow struct {
	SkillID int32  `json:"skill_id"`
	Name    string `json:"name"`
}

func (q *Queries) GetQuestSkills(ctx context.Context, arg GetQuestSkillsParams) ([]GetQuestSkillsRow, error) {
	rows, err := q.db.Query(ctx, getQuestSkills, arg.UserID, arg.QuestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuestSkillsRow
	for rows.Next() {
		var i GetQuestSkillsRow
		if err := rows.Scan(&i.SkillID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSkillsForQuest = `-- name: GetSkillsForQuest :many
SELECT skill_id FROM quests_skills WHERE quest_id = $1
`

func (q *Queries) GetSkillsForQuest(ctx context.Context, questID int64) ([]int32, error) {
	rows, err := q.db.Query(ctx, getSkillsForQuest, questID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var skill_id int32
		if err := rows.Scan(&skill_id); err != nil {
			return nil, err
		}
		items = append(items, skill_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubQuests = `-- name: GetSubQuests :many
SELECT id, type, name, experience, completed FROM quests
WHERE user_id = $1
  AND deleted_at IS NULL
  AND parent_quest_id = $2
ORDER BY completed
`

type GetSubQuestsParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	ParentQuestID pgtype.Int8 `json:"parent_quest_id"`
}

type GetSubQuestsRow struct {
	ID         int64       `json:"id"`
	Type       pgtype.Text `json:"type"`
	Name       string      `json:"name"`
	Experience pgtype.Int4 `json:"experience"`
	Completed  pgtype.Bool `json:"completed"`
}

func (q *Queries) GetSubQuests(ctx context.Context, arg GetSubQuestsParams) ([]GetSubQuestsRow, error) {
	rows, err := q.db.Query(ctx, getSubQuests, arg.UserID, arg.ParentQuestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubQuestsRow
	for rows.Next() {
		var i GetSubQuestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Experience,
			&i.Completed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubQuestsIDs = `-- name: GetSubQuestsIDs :many
SELECT id FROM quests WHERE parent_quest_id = $1
`

func (q *Queries) GetSubQuestsIDs(ctx context.Context, parentQuestID pgtype.Int8) ([]int64, error) {
	rows, err := q.db.Query(ctx, getSubQuestsIDs, parentQuestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersCustomQuests = `-- name: GetUsersCustomQuests :many
SELECT q.id, q.type, q.name, q.experience, q.completed, q.start_date, q.end_date,
  (
    SELECT COUNT(*)
    FROM quests sub
    WHERE sub.parent_quest_id = q.id
      AND sub.user_id = q.user_id
      AND sub.deleted_at IS NULL
      AND sub.completed = true
  ) as completed_sub_quests
FROM quests q
WHERE q.user_id = $1 
  AND q.deleted_at IS NULL
  AND q.type = 'custom'
ORDER BY COALESCE(q.completed, false)
`

type GetUsersCustomQuestsRow struct {
	ID                 int64       `json:"id"`
	Type               pgtype.Text `json:"type"`
	Name               string      `json:"name"`
	Experience         pgtype.Int4 `json:"experience"`
	Completed          pgtype.Bool `json:"completed"`
	StartDate          pgtype.Date `json:"start_date"`
	EndDate            pgtype.Date `json:"end_date"`
	CompletedSubQuests int64       `json:"completed_sub_quests"`
}

func (q *Queries) GetUsersCustomQuests(ctx context.Context, userID uuid.UUID) ([]GetUsersCustomQuestsRow, error) {
	rows, err := q.db.Query(ctx, getUsersCustomQuests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersCustomQuestsRow
	for rows.Next() {
		var i GetUsersCustomQuestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Experience,
			&i.Completed,
			&i.StartDate,
			&i.EndDate,
			&i.CompletedSubQuests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersRepeatingQuests = `-- name: GetUsersRepeatingQuests :many
SELECT q.id, q.type, q.name, q.experience, q.completed,
  (
    SELECT COUNT(*)
    FROM quests sub
    WHERE sub.parent_quest_id = q.id
      AND sub.user_id = q.user_id
      AND sub.deleted_at IS NULL
      AND sub.completed = true
  ) as completed_sub_quests
FROM quests q
WHERE q.user_id = $1
  AND q.deleted_at IS NULL 
  AND q.type != 'custom'
  AND q.parent_quest_id IS NULL
ORDER BY q.type, COALESCE(q.completed, false), q.name
`

type GetUsersRepeatingQuestsRow struct {
	ID                 int64       `json:"id"`
	Type               pgtype.Text `json:"type"`
	Name               string      `json:"name"`
	Experience         pgtype.Int4 `json:"experience"`
	Completed          pgtype.Bool `json:"completed"`
	CompletedSubQuests int64       `json:"completed_sub_quests"`
}

func (q *Queries) GetUsersRepeatingQuests(ctx context.Context, userID uuid.UUID) ([]GetUsersRepeatingQuestsRow, error) {
	rows, err := q.db.Query(ctx, getUsersRepeatingQuests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersRepeatingQuestsRow
	for rows.Next() {
		var i GetUsersRepeatingQuestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Experience,
			&i.Completed,
			&i.CompletedSubQuests,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuest = `-- name: UpdateQuest :exec
UPDATE quests
SET
  updated_at = NOW(),
  name = $2,
  type = $3,
  experience = $4,
  start_date = $5,
  end_date = $6
WHERE id = $1
`

type UpdateQuestParams struct {
	ID         int64       `json:"id"`
	Name       string      `json:"name"`
	Type       pgtype.Text `json:"type"`
	Experience pgtype.Int4 `json:"experience"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
}

func (q *Queries) UpdateQuest(ctx context.Context, arg UpdateQuestParams) error {
	_, err := q.db.Exec(ctx, updateQuest,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Experience,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}
