// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quests.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createQuest = `-- name: CreateQuest :exec
INSERT INTO quests(created_at, updated_at, name, experience, user_id) VALUES (NOW(), NOW(), $1, $2, $3)
`

type CreateQuestParams struct {
	Name       string        `json:"name"`
	Experience sql.NullInt32 `json:"experience"`
	UserID     uuid.UUID     `json:"user_id"`
}

func (q *Queries) CreateQuest(ctx context.Context, arg CreateQuestParams) error {
	_, err := q.db.ExecContext(ctx, createQuest, arg.Name, arg.Experience, arg.UserID)
	return err
}
