// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package database

import (
	"context"
)

const createSkill = `-- name: CreateSkill :exec
INSERT INTO skills(created_at, updated_at, name) VALUES (NOW(), NOW(), $1)
`

func (q *Queries) CreateSkill(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, createSkill, name)
	return err
}

const getAllSkills = `-- name: GetAllSkills :many
SELECT name FROM skills ORDER BY name LIMIT 200
`

func (q *Queries) GetAllSkills(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAllSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSkillsByName = `-- name: GetSkillsByName :many
SELECT id, name FROM skills WHERE name LIKE $1 ORDER BY name LIMIT 200
`

type GetSkillsByNameRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetSkillsByName(ctx context.Context, name string) ([]GetSkillsByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getSkillsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSkillsByNameRow
	for rows.Next() {
		var i GetSkillsByNameRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
