// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills(created_at, updated_at, name) VALUES (NOW(), NOW(), $1) RETURNING id
`

func (q *Queries) CreateSkill(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, createSkill, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getAllSkills = `-- name: GetAllSkills :many
SELECT name FROM skills ORDER BY name LIMIT 200
`

func (q *Queries) GetAllSkills(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getAllSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSkillsByName = `-- name: GetSkillsByName :many
SELECT id, name FROM skills WHERE name LIKE $1 ORDER BY name LIMIT 200
`

type GetSkillsByNameRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetSkillsByName(ctx context.Context, name string) ([]GetSkillsByNameRow, error) {
	rows, err := q.db.Query(ctx, getSkillsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSkillsByNameRow
	for rows.Next() {
		var i GetSkillsByNameRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSkillsNotOwnedByUser = `-- name: GetSkillsNotOwnedByUser :many
SELECT s.id, s.name FROM skills s
WHERE s.name LIKE $1 AND NOT EXISTS (
  SELECT 1
  FROM users_skills us
  WHERE us.user_id = $2
    AND us.skill_id = s.id
    AND us.deleted_at IS NULL
)
LIMIT 200
`

type GetSkillsNotOwnedByUserParams struct {
	Name   string    `json:"name"`
	UserID uuid.UUID `json:"user_id"`
}

type GetSkillsNotOwnedByUserRow struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetSkillsNotOwnedByUser(ctx context.Context, arg GetSkillsNotOwnedByUserParams) ([]GetSkillsNotOwnedByUserRow, error) {
	rows, err := q.db.Query(ctx, getSkillsNotOwnedByUser, arg.Name, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSkillsNotOwnedByUserRow
	for rows.Next() {
		var i GetSkillsNotOwnedByUserRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersSkillsLinkedName = `-- name: GetUsersSkillsLinkedName :one
SELECT name FROM skills WHERE id = $1
`

func (q *Queries) GetUsersSkillsLinkedName(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getUsersSkillsLinkedName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
