// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(id, created_at, updated_at, email, password)
VALUES(
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2
) RETURNING id, email
`

type CreateUserParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateUserRow struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.Password)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, firstname, lastname, nickname, dateofbirth, email, password, hot_streak, quests_completed, repeating_completed, customs_completed, experience, experience_needed, level FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Firstname,
		&i.Lastname,
		&i.Nickname,
		&i.Dateofbirth,
		&i.Email,
		&i.Password,
		&i.HotStreak,
		&i.QuestsCompleted,
		&i.RepeatingCompleted,
		&i.CustomsCompleted,
		&i.Experience,
		&i.ExperienceNeeded,
		&i.Level,
	)
	return i, err
}
