// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_stats.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUsersStatsById = `-- name: GetUsersStatsById :one
SELECT user_id, quests_completed, repeating_quests_completed, custom_quests_completed, quest_experience_gained, skill_experience_gained, updated_at FROM users_stats WHERE user_id = $1
`

func (q *Queries) GetUsersStatsById(ctx context.Context, userID uuid.UUID) (UsersStat, error) {
	row := q.db.QueryRowContext(ctx, getUsersStatsById, userID)
	var i UsersStat
	err := row.Scan(
		&i.UserID,
		&i.QuestsCompleted,
		&i.RepeatingQuestsCompleted,
		&i.CustomQuestsCompleted,
		&i.QuestExperienceGained,
		&i.SkillExperienceGained,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUsersStats = `-- name: UpdateUsersStats :exec
UPDATE users_stats
SET
  quests_completed = quests_completed + 1,
  repeating_quests_completed = repeating_quests_completed + CASE WHEN $1 = 'd' OR 'w' OR 'm' OR 'y' THEN 1 ELSE 0 END,
  custom_quests_completed = custom_quests_completed + CASE WHEN $1 = 'custom' THEN 1 ELSE 0 END,
  quest_experience_gained = quest_experience_gained + $2,
  updated_at = NOW()
WHERE user_id = $3
`

type UpdateUsersStatsParams struct {
	Column1               interface{} `json:"column_1"`
	QuestExperienceGained int32       `json:"quest_experience_gained"`
	UserID                uuid.UUID   `json:"user_id"`
}

func (q *Queries) UpdateUsersStats(ctx context.Context, arg UpdateUsersStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateUsersStats, arg.Column1, arg.QuestExperienceGained, arg.UserID)
	return err
}
