// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_skills.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUsersSkills = `-- name: CreateUsersSkills :exec
INSERT INTO users_skills(
  user_id,
  skill_id,
  created_at,
  updated_at,
  name,
  experience,
  experience_needed,
  level
) VALUES (
  $1,
  $2,
  NOW(),
  NOW(),
  $3,
  0,
  100,
  1
)
ON CONFLICT (user_id, skill_id)
DO UPDATE SET
  deleted_at = NULL,
  deleted_reason = NULL,
  updated_at = NOW()
`

type CreateUsersSkillsParams struct {
	UserID  uuid.UUID `json:"user_id"`
	SkillID int32     `json:"skill_id"`
	Name    string    `json:"name"`
}

func (q *Queries) CreateUsersSkills(ctx context.Context, arg CreateUsersSkillsParams) error {
	_, err := q.db.Exec(ctx, createUsersSkills, arg.UserID, arg.SkillID, arg.Name)
	return err
}

const deactivateRemovedLinkedSkills = `-- name: DeactivateRemovedLinkedSkills :exec
UPDATE users_skills_links
SET deleted_at = NOW(),
    deleted_reason = 'manual',
    updated_at = NOW()
WHERE user_id = $1
  AND parent_skill_id = $2
  AND deleted_at IS NULL
  AND child_skill_id != ALL($3::int[])
`

type DeactivateRemovedLinkedSkillsParams struct {
	UserID        uuid.UUID `json:"user_id"`
	ParentSkillID int32     `json:"parent_skill_id"`
	Column3       []int32   `json:"column_3"`
}

func (q *Queries) DeactivateRemovedLinkedSkills(ctx context.Context, arg DeactivateRemovedLinkedSkillsParams) error {
	_, err := q.db.Exec(ctx, deactivateRemovedLinkedSkills, arg.UserID, arg.ParentSkillID, arg.Column3)
	return err
}

const getMostRecentLeveledSkill = `-- name: GetMostRecentLeveledSkill :one
SELECT name FROM users_skills
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY leveled_at DESC
LIMIT 1
`

func (q *Queries) GetMostRecentLeveledSkill(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getMostRecentLeveledSkill, userID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getSkillsExperience = `-- name: GetSkillsExperience :one
SELECT experience, experience_needed, level FROM users_skills WHERE skill_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetSkillsExperienceParams struct {
	SkillID int32     `json:"skill_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type GetSkillsExperienceRow struct {
	Experience       int32 `json:"experience"`
	ExperienceNeeded int32 `json:"experience_needed"`
	Level            int32 `json:"level"`
}

func (q *Queries) GetSkillsExperience(ctx context.Context, arg GetSkillsExperienceParams) (GetSkillsExperienceRow, error) {
	row := q.db.QueryRow(ctx, getSkillsExperience, arg.SkillID, arg.UserID)
	var i GetSkillsExperienceRow
	err := row.Scan(&i.Experience, &i.ExperienceNeeded, &i.Level)
	return i, err
}

const getUserSkillID = `-- name: GetUserSkillID :one
SELECT skill_id FROM users_skills WHERE user_id = $1 AND name = $2
`

type GetUserSkillIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) GetUserSkillID(ctx context.Context, arg GetUserSkillIDParams) (int32, error) {
	row := q.db.QueryRow(ctx, getUserSkillID, arg.UserID, arg.Name)
	var skill_id int32
	err := row.Scan(&skill_id)
	return skill_id, err
}

const getUsersSkillHighestLevel = `-- name: GetUsersSkillHighestLevel :one
SELECT name FROM users_skills
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY level DESC, experience DESC
LIMIT 1
`

func (q *Queries) GetUsersSkillHighestLevel(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUsersSkillHighestLevel, userID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getUsersSkills = `-- name: GetUsersSkills :many
SELECT
  parent.skill_id,
  parent.name,
  parent.experience,
  parent.experience_needed,
  parent.level,
COALESCE(
  jsonb_agg(
    jsonb_build_object(
      'id', child.skill_id,
      'name', child.name
    )
  ) FILTER (WHERE child.skill_id IS NOT NULL),
  '[]'::jsonb
)::text AS linked_skills
FROM users_skills parent
LEFT JOIN users_skills_links link
  ON link.user_id = parent.user_id
  AND link.parent_skill_id = parent.skill_id
  AND link.deleted_at IS NULL
LEFT JOIN users_skills child
  ON child.user_id = parent.user_id
  AND child.skill_id = link.child_skill_id
  AND child.deleted_at IS NULL
WHERE parent.user_id = $1
  AND parent.deleted_at IS NULL
GROUP BY
  parent.skill_id,
  parent.name,
  parent.experience,
  parent.experience_needed,
  parent.level
`

type GetUsersSkillsRow struct {
	SkillID          int32  `json:"skill_id"`
	Name             string `json:"name"`
	Experience       int32  `json:"experience"`
	ExperienceNeeded int32  `json:"experience_needed"`
	Level            int32  `json:"level"`
	LinkedSkills     string `json:"linked_skills"`
}

func (q *Queries) GetUsersSkills(ctx context.Context, userID uuid.UUID) ([]GetUsersSkillsRow, error) {
	rows, err := q.db.Query(ctx, getUsersSkills, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersSkillsRow
	for rows.Next() {
		var i GetUsersSkillsRow
		if err := rows.Scan(
			&i.SkillID,
			&i.Name,
			&i.Experience,
			&i.ExperienceNeeded,
			&i.Level,
			&i.LinkedSkills,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersSkillsExclude = `-- name: GetUsersSkillsExclude :many
SELECT name, skill_id FROM users_skills
WHERE user_id = $1
  AND name LIKE $2
  AND skill_id != ALL($3::int[])
  AND name != $4
  AND deleted_at IS NULL
`

type GetUsersSkillsExcludeParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Name    string    `json:"name"`
	Column3 []int32   `json:"column_3"`
	Name_2  string    `json:"name_2"`
}

type GetUsersSkillsExcludeRow struct {
	Name    string `json:"name"`
	SkillID int32  `json:"skill_id"`
}

func (q *Queries) GetUsersSkillsExclude(ctx context.Context, arg GetUsersSkillsExcludeParams) ([]GetUsersSkillsExcludeRow, error) {
	rows, err := q.db.Query(ctx, getUsersSkillsExclude,
		arg.UserID,
		arg.Name,
		arg.Column3,
		arg.Name_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersSkillsExcludeRow
	for rows.Next() {
		var i GetUsersSkillsExcludeRow
		if err := rows.Scan(&i.Name, &i.SkillID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersSkillsLinkedID = `-- name: GetUsersSkillsLinkedID :many
SELECT child_skill_id FROM users_skills_links
WHERE parent_skill_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetUsersSkillsLinkedIDParams struct {
	ParentSkillID int32     `json:"parent_skill_id"`
	UserID        uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUsersSkillsLinkedID(ctx context.Context, arg GetUsersSkillsLinkedIDParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, getUsersSkillsLinkedID, arg.ParentSkillID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var child_skill_id int32
		if err := rows.Scan(&child_skill_id); err != nil {
			return nil, err
		}
		items = append(items, child_skill_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUserSkill = `-- name: SoftDeleteUserSkill :exec
WITH deleted_skill AS (
  UPDATE users_skills
  SET
    deleted_at = NOW(),
    deleted_reason = 'manual',
    updated_at = NOW()
  WHERE users_skills.user_id = $1
    AND users_skills.skill_id = $2
    AND users_skills.deleted_at IS NULL
)
UPDATE users_skills_links
SET
  deleted_at = NOW(),
  deleted_reason = CASE
    WHEN parent_skill_id = $2 THEN 'parent_skill_deleted'
    WHEN child_skill_id = $2 THEN 'child_skill_deleted'
  END,
  updated_at = NOW()
WHERE users_skills_links.user_id = $1
  AND users_skills_links.deleted_at IS NULL
  AND (
    parent_skill_id = $2
    OR child_skill_id = $2
  )
`

type SoftDeleteUserSkillParams struct {
	UserID        uuid.UUID `json:"user_id"`
	ParentSkillID int32     `json:"parent_skill_id"`
}

func (q *Queries) SoftDeleteUserSkill(ctx context.Context, arg SoftDeleteUserSkillParams) error {
	_, err := q.db.Exec(ctx, softDeleteUserSkill, arg.UserID, arg.ParentSkillID)
	return err
}

const updateSkillsExperience = `-- name: UpdateSkillsExperience :exec
UPDATE users_skills SET updated_at = NOW(), experience = $3, experience_needed = $4, level = $5 WHERE skill_id = $1 AND user_id = $2
`

type UpdateSkillsExperienceParams struct {
	SkillID          int32     `json:"skill_id"`
	UserID           uuid.UUID `json:"user_id"`
	Experience       int32     `json:"experience"`
	ExperienceNeeded int32     `json:"experience_needed"`
	Level            int32     `json:"level"`
}

func (q *Queries) UpdateSkillsExperience(ctx context.Context, arg UpdateSkillsExperienceParams) error {
	_, err := q.db.Exec(ctx, updateSkillsExperience,
		arg.SkillID,
		arg.UserID,
		arg.Experience,
		arg.ExperienceNeeded,
		arg.Level,
	)
	return err
}

const upsertLinkedSkills = `-- name: UpsertLinkedSkills :exec
INSERT INTO users_skills_links (
  user_id,
  parent_skill_id,
  child_skill_id,
  created_at,
  updated_at,
  deleted_at
)
SELECT
  $1,
  $2,
  child_id,
  NOW(),
  NOW(),
  NULL
FROM unnest($3::int[]) AS child_id
ON CONFLICT (user_id, parent_skill_id, child_skill_id)
DO UPDATE SET
  deleted_at = NULL,
  deleted_reason = NULL,
  updated_at = NOW()
`

type UpsertLinkedSkillsParams struct {
	UserID        uuid.UUID `json:"user_id"`
	ParentSkillID int32     `json:"parent_skill_id"`
	Column3       []int32   `json:"column_3"`
}

func (q *Queries) UpsertLinkedSkills(ctx context.Context, arg UpsertLinkedSkillsParams) error {
	_, err := q.db.Exec(ctx, upsertLinkedSkills, arg.UserID, arg.ParentSkillID, arg.Column3)
	return err
}
