// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_skills.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUsersSkills = `-- name: CreateUsersSkills :exec
INSERT INTO users_skills(user_id, skill_id, created_at, updated_at, name, experience, experience_needed, level) VALUES ($1, $2, NOW(), NOW(), $3, 0, 100, 1)
`

type CreateUsersSkillsParams struct {
	UserID  uuid.UUID `json:"user_id"`
	SkillID int32     `json:"skill_id"`
	Name    string    `json:"name"`
}

func (q *Queries) CreateUsersSkills(ctx context.Context, arg CreateUsersSkillsParams) error {
	_, err := q.db.ExecContext(ctx, createUsersSkills, arg.UserID, arg.SkillID, arg.Name)
	return err
}

const createUsersSkillsLinks = `-- name: CreateUsersSkillsLinks :exec
INSERT INTO users_skills_links(user_id, parent_skill_id, child_skill_id, created_at, updated_at) VALUES ($1, $2, $3, NOW(), NOW())
`

type CreateUsersSkillsLinksParams struct {
	UserID        uuid.UUID `json:"user_id"`
	ParentSkillID int32     `json:"parent_skill_id"`
	ChildSkillID  int32     `json:"child_skill_id"`
}

func (q *Queries) CreateUsersSkillsLinks(ctx context.Context, arg CreateUsersSkillsLinksParams) error {
	_, err := q.db.ExecContext(ctx, createUsersSkillsLinks, arg.UserID, arg.ParentSkillID, arg.ChildSkillID)
	return err
}

const getUserSkillID = `-- name: GetUserSkillID :one
SELECT skill_id FROM users_skills WHERE user_id = $1 AND name = $2
`

type GetUserSkillIDParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) GetUserSkillID(ctx context.Context, arg GetUserSkillIDParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserSkillID, arg.UserID, arg.Name)
	var skill_id int32
	err := row.Scan(&skill_id)
	return skill_id, err
}
