/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DatabaseGetSkillsByNameRow
 */
export interface DatabaseGetSkillsByNameRow {
    /**
     * 
     * @type {number}
     * @memberof DatabaseGetSkillsByNameRow
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetSkillsByNameRow
     */
    name?: string;
}

/**
 * Check if a given object implements the DatabaseGetSkillsByNameRow interface.
 */
export function instanceOfDatabaseGetSkillsByNameRow(value: object): value is DatabaseGetSkillsByNameRow {
    return true;
}

export function DatabaseGetSkillsByNameRowFromJSON(json: any): DatabaseGetSkillsByNameRow {
    return DatabaseGetSkillsByNameRowFromJSONTyped(json, false);
}

export function DatabaseGetSkillsByNameRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatabaseGetSkillsByNameRow {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function DatabaseGetSkillsByNameRowToJSON(json: any): DatabaseGetSkillsByNameRow {
    return DatabaseGetSkillsByNameRowToJSONTyped(json, false);
}

export function DatabaseGetSkillsByNameRowToJSONTyped(value?: DatabaseGetSkillsByNameRow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

