/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DatabaseGetSkillsNotOwnedByUserRow
 */
export interface DatabaseGetSkillsNotOwnedByUserRow {
    /**
     * 
     * @type {number}
     * @memberof DatabaseGetSkillsNotOwnedByUserRow
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof DatabaseGetSkillsNotOwnedByUserRow
     */
    name?: string;
}

/**
 * Check if a given object implements the DatabaseGetSkillsNotOwnedByUserRow interface.
 */
export function instanceOfDatabaseGetSkillsNotOwnedByUserRow(value: object): value is DatabaseGetSkillsNotOwnedByUserRow {
    return true;
}

export function DatabaseGetSkillsNotOwnedByUserRowFromJSON(json: any): DatabaseGetSkillsNotOwnedByUserRow {
    return DatabaseGetSkillsNotOwnedByUserRowFromJSONTyped(json, false);
}

export function DatabaseGetSkillsNotOwnedByUserRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatabaseGetSkillsNotOwnedByUserRow {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function DatabaseGetSkillsNotOwnedByUserRowToJSON(json: any): DatabaseGetSkillsNotOwnedByUserRow {
    return DatabaseGetSkillsNotOwnedByUserRowToJSONTyped(json, false);
}

export function DatabaseGetSkillsNotOwnedByUserRowToJSONTyped(value?: DatabaseGetSkillsNotOwnedByUserRow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

