/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainSkill
 */
export interface MainSkill {
    /**
     * 
     * @type {object}
     * @memberof MainSkill
     */
    linkedSkills?: object;
    /**
     * 
     * @type {number}
     * @memberof MainSkill
     */
    experience?: number;
    /**
     * 
     * @type {number}
     * @memberof MainSkill
     */
    experienceNeeded?: number;
    /**
     * 
     * @type {number}
     * @memberof MainSkill
     */
    level?: number;
    /**
     * 
     * @type {string}
     * @memberof MainSkill
     */
    name: string;
}

/**
 * Check if a given object implements the MainSkill interface.
 */
export function instanceOfMainSkill(value: object): value is MainSkill {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MainSkillFromJSON(json: any): MainSkill {
    return MainSkillFromJSONTyped(json, false);
}

export function MainSkillFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainSkill {
    if (json == null) {
        return json;
    }
    return {
        
        'linkedSkills': json['LinkedSkills'] == null ? undefined : json['LinkedSkills'],
        'experience': json['experience'] == null ? undefined : json['experience'],
        'experienceNeeded': json['experience_needed'] == null ? undefined : json['experience_needed'],
        'level': json['level'] == null ? undefined : json['level'],
        'name': json['name'],
    };
}

export function MainSkillToJSON(json: any): MainSkill {
    return MainSkillToJSONTyped(json, false);
}

export function MainSkillToJSONTyped(value?: MainSkill | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'LinkedSkills': value['linkedSkills'],
        'experience': value['experience'],
        'experience_needed': value['experienceNeeded'],
        'level': value['level'],
        'name': value['name'],
    };
}

