/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainSkillExclude } from './MainSkillExclude';
import {
    MainSkillExcludeFromJSON,
    MainSkillExcludeFromJSONTyped,
    MainSkillExcludeToJSON,
    MainSkillExcludeToJSONTyped,
} from './MainSkillExclude';

/**
 * 
 * @export
 * @interface MainSkillsExcludeResponse
 */
export interface MainSkillsExcludeResponse {
    /**
     * 
     * @type {Array<MainSkillExclude>}
     * @memberof MainSkillsExcludeResponse
     */
    skills?: Array<MainSkillExclude>;
}

/**
 * Check if a given object implements the MainSkillsExcludeResponse interface.
 */
export function instanceOfMainSkillsExcludeResponse(value: object): value is MainSkillsExcludeResponse {
    return true;
}

export function MainSkillsExcludeResponseFromJSON(json: any): MainSkillsExcludeResponse {
    return MainSkillsExcludeResponseFromJSONTyped(json, false);
}

export function MainSkillsExcludeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainSkillsExcludeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'skills': json['skills'] == null ? undefined : ((json['skills'] as Array<any>).map(MainSkillExcludeFromJSON)),
    };
}

export function MainSkillsExcludeResponseToJSON(json: any): MainSkillsExcludeResponse {
    return MainSkillsExcludeResponseToJSONTyped(json, false);
}

export function MainSkillsExcludeResponseToJSONTyped(value?: MainSkillsExcludeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skills': value['skills'] == null ? undefined : ((value['skills'] as Array<any>).map(MainSkillExcludeToJSON)),
    };
}

