/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainRepeatingQuest } from './MainRepeatingQuest';
import {
    MainRepeatingQuestFromJSON,
    MainRepeatingQuestFromJSONTyped,
    MainRepeatingQuestToJSON,
    MainRepeatingQuestToJSONTyped,
} from './MainRepeatingQuest';
import type { MainSkillCreationPayload } from './MainSkillCreationPayload';
import {
    MainSkillCreationPayloadFromJSON,
    MainSkillCreationPayloadFromJSONTyped,
    MainSkillCreationPayloadToJSON,
    MainSkillCreationPayloadToJSONTyped,
} from './MainSkillCreationPayload';

/**
 * 
 * @export
 * @interface MainQuestCreationPayload
 */
export interface MainQuestCreationPayload {
    /**
     * 
     * @type {string}
     * @memberof MainQuestCreationPayload
     */
    endDate?: string;
    /**
     * 
     * @type {number}
     * @memberof MainQuestCreationPayload
     */
    experience?: number;
    /**
     * 
     * @type {number}
     * @memberof MainQuestCreationPayload
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MainQuestCreationPayload
     */
    name?: string;
    /**
     * 
     * @type {Array<MainSkillCreationPayload>}
     * @memberof MainQuestCreationPayload
     */
    skills?: Array<MainSkillCreationPayload>;
    /**
     * 
     * @type {string}
     * @memberof MainQuestCreationPayload
     */
    startDate?: string;
    /**
     * 
     * @type {Array<MainRepeatingQuest>}
     * @memberof MainQuestCreationPayload
     */
    subQuests?: Array<MainRepeatingQuest>;
    /**
     * 
     * @type {string}
     * @memberof MainQuestCreationPayload
     */
    type?: string;
}

/**
 * Check if a given object implements the MainQuestCreationPayload interface.
 */
export function instanceOfMainQuestCreationPayload(value: object): value is MainQuestCreationPayload {
    return true;
}

export function MainQuestCreationPayloadFromJSON(json: any): MainQuestCreationPayload {
    return MainQuestCreationPayloadFromJSONTyped(json, false);
}

export function MainQuestCreationPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainQuestCreationPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'endDate': json['endDate'] == null ? undefined : json['endDate'],
        'experience': json['experience'] == null ? undefined : json['experience'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'skills': json['skills'] == null ? undefined : ((json['skills'] as Array<any>).map(MainSkillCreationPayloadFromJSON)),
        'startDate': json['startDate'] == null ? undefined : json['startDate'],
        'subQuests': json['subQuests'] == null ? undefined : ((json['subQuests'] as Array<any>).map(MainRepeatingQuestFromJSON)),
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function MainQuestCreationPayloadToJSON(json: any): MainQuestCreationPayload {
    return MainQuestCreationPayloadToJSONTyped(json, false);
}

export function MainQuestCreationPayloadToJSONTyped(value?: MainQuestCreationPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endDate': value['endDate'],
        'experience': value['experience'],
        'id': value['id'],
        'name': value['name'],
        'skills': value['skills'] == null ? undefined : ((value['skills'] as Array<any>).map(MainSkillCreationPayloadToJSON)),
        'startDate': value['startDate'],
        'subQuests': value['subQuests'] == null ? undefined : ((value['subQuests'] as Array<any>).map(MainRepeatingQuestToJSON)),
        'type': value['type'],
    };
}

