/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainTypeRepeatingQuest } from './MainTypeRepeatingQuest';
import {
    MainTypeRepeatingQuestFromJSON,
    MainTypeRepeatingQuestFromJSONTyped,
    MainTypeRepeatingQuestToJSON,
    MainTypeRepeatingQuestToJSONTyped,
} from './MainTypeRepeatingQuest';
import type { MainCustomQuest } from './MainCustomQuest';
import {
    MainCustomQuestFromJSON,
    MainCustomQuestFromJSONTyped,
    MainCustomQuestToJSON,
    MainCustomQuestToJSONTyped,
} from './MainCustomQuest';

/**
 * 
 * @export
 * @interface MainQuestsReponse
 */
export interface MainQuestsReponse {
    /**
     * 
     * @type {Array<MainCustomQuest>}
     * @memberof MainQuestsReponse
     */
    customQuests?: Array<MainCustomQuest>;
    /**
     * 
     * @type {Array<MainTypeRepeatingQuest>}
     * @memberof MainQuestsReponse
     */
    repeatingQuests?: Array<MainTypeRepeatingQuest>;
}

/**
 * Check if a given object implements the MainQuestsReponse interface.
 */
export function instanceOfMainQuestsReponse(value: object): value is MainQuestsReponse {
    return true;
}

export function MainQuestsReponseFromJSON(json: any): MainQuestsReponse {
    return MainQuestsReponseFromJSONTyped(json, false);
}

export function MainQuestsReponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainQuestsReponse {
    if (json == null) {
        return json;
    }
    return {
        
        'customQuests': json['customQuests'] == null ? undefined : ((json['customQuests'] as Array<any>).map(MainCustomQuestFromJSON)),
        'repeatingQuests': json['repeatingQuests'] == null ? undefined : ((json['repeatingQuests'] as Array<any>).map(MainTypeRepeatingQuestFromJSON)),
    };
}

export function MainQuestsReponseToJSON(json: any): MainQuestsReponse {
    return MainQuestsReponseToJSONTyped(json, false);
}

export function MainQuestsReponseToJSONTyped(value?: MainQuestsReponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customQuests': value['customQuests'] == null ? undefined : ((value['customQuests'] as Array<any>).map(MainCustomQuestToJSON)),
        'repeatingQuests': value['repeatingQuests'] == null ? undefined : ((value['repeatingQuests'] as Array<any>).map(MainTypeRepeatingQuestToJSON)),
    };
}

