/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainProfileResponse } from './MainProfileResponse';
import {
    MainProfileResponseFromJSON,
    MainProfileResponseFromJSONTyped,
    MainProfileResponseToJSON,
    MainProfileResponseToJSONTyped,
} from './MainProfileResponse';

/**
 * 
 * @export
 * @interface MainUserResponse
 */
export interface MainUserResponse {
    /**
     * 
     * @type {string}
     * @memberof MainUserResponse
     */
    bio?: string;
    /**
     * 
     * @type {MainProfileResponse}
     * @memberof MainUserResponse
     */
    profile: MainProfileResponse;
}

/**
 * Check if a given object implements the MainUserResponse interface.
 */
export function instanceOfMainUserResponse(value: object): value is MainUserResponse {
    if (!('profile' in value) || value['profile'] === undefined) return false;
    return true;
}

export function MainUserResponseFromJSON(json: any): MainUserResponse {
    return MainUserResponseFromJSONTyped(json, false);
}

export function MainUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bio': json['bio'] == null ? undefined : json['bio'],
        'profile': MainProfileResponseFromJSON(json['profile']),
    };
}

export function MainUserResponseToJSON(json: any): MainUserResponse {
    return MainUserResponseToJSONTyped(json, false);
}

export function MainUserResponseToJSONTyped(value?: MainUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bio': value['bio'],
        'profile': MainProfileResponseToJSON(value['profile']),
    };
}

