/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainSkillsCreation
 */
export interface MainSkillsCreation {
    /**
     * 
     * @type {number}
     * @memberof MainSkillsCreation
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MainSkillsCreation
     */
    name?: string;
}

/**
 * Check if a given object implements the MainSkillsCreation interface.
 */
export function instanceOfMainSkillsCreation(value: object): value is MainSkillsCreation {
    return true;
}

export function MainSkillsCreationFromJSON(json: any): MainSkillsCreation {
    return MainSkillsCreationFromJSONTyped(json, false);
}

export function MainSkillsCreationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainSkillsCreation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function MainSkillsCreationToJSON(json: any): MainSkillsCreation {
    return MainSkillsCreationToJSONTyped(json, false);
}

export function MainSkillsCreationToJSONTyped(value?: MainSkillsCreation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

