/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainSkill } from './MainSkill';
import {
    MainSkillFromJSON,
    MainSkillFromJSONTyped,
    MainSkillToJSON,
    MainSkillToJSONTyped,
} from './MainSkill';

/**
 * 
 * @export
 * @interface MainUsersSkillsResponse
 */
export interface MainUsersSkillsResponse {
    /**
     * 
     * @type {Array<MainSkill>}
     * @memberof MainUsersSkillsResponse
     */
    skills?: Array<MainSkill>;
}

/**
 * Check if a given object implements the MainUsersSkillsResponse interface.
 */
export function instanceOfMainUsersSkillsResponse(value: object): value is MainUsersSkillsResponse {
    return true;
}

export function MainUsersSkillsResponseFromJSON(json: any): MainUsersSkillsResponse {
    return MainUsersSkillsResponseFromJSONTyped(json, false);
}

export function MainUsersSkillsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainUsersSkillsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'skills': json['skills'] == null ? undefined : ((json['skills'] as Array<any>).map(MainSkillFromJSON)),
    };
}

export function MainUsersSkillsResponseToJSON(json: any): MainUsersSkillsResponse {
    return MainUsersSkillsResponseToJSONTyped(json, false);
}

export function MainUsersSkillsResponseToJSONTyped(value?: MainUsersSkillsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skills': value['skills'] == null ? undefined : ((value['skills'] as Array<any>).map(MainSkillToJSON)),
    };
}

