/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainLoginResponse
 */
export interface MainLoginResponse {
    /**
     * 
     * @type {string}
     * @memberof MainLoginResponse
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof MainLoginResponse
     */
    redirect?: string;
}

/**
 * Check if a given object implements the MainLoginResponse interface.
 */
export function instanceOfMainLoginResponse(value: object): value is MainLoginResponse {
    return true;
}

export function MainLoginResponseFromJSON(json: any): MainLoginResponse {
    return MainLoginResponseFromJSONTyped(json, false);
}

export function MainLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainLoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'redirect': json['redirect'] == null ? undefined : json['redirect'],
    };
}

export function MainLoginResponseToJSON(json: any): MainLoginResponse {
    return MainLoginResponseToJSONTyped(json, false);
}

export function MainLoginResponseToJSONTyped(value?: MainLoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'redirect': value['redirect'],
    };
}

