/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainQuestsCreation
 */
export interface MainQuestsCreation {
    /**
     * 
     * @type {number}
     * @memberof MainQuestsCreation
     */
    experience?: number;
    /**
     * 
     * @type {string}
     * @memberof MainQuestsCreation
     */
    name?: string;
}

/**
 * Check if a given object implements the MainQuestsCreation interface.
 */
export function instanceOfMainQuestsCreation(value: object): value is MainQuestsCreation {
    return true;
}

export function MainQuestsCreationFromJSON(json: any): MainQuestsCreation {
    return MainQuestsCreationFromJSONTyped(json, false);
}

export function MainQuestsCreationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainQuestsCreation {
    if (json == null) {
        return json;
    }
    return {
        
        'experience': json['experience'] == null ? undefined : json['experience'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function MainQuestsCreationToJSON(json: any): MainQuestsCreation {
    return MainQuestsCreationToJSONTyped(json, false);
}

export function MainQuestsCreationToJSONTyped(value?: MainQuestsCreation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'experience': value['experience'],
        'name': value['name'],
    };
}

