/* tslint:disable */
/* eslint-disable */
/**
 * Your API Title
 * This is a sample API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainTestResponseTwo
 */
export interface MainTestResponseTwo {
    /**
     * 
     * @type {string}
     * @memberof MainTestResponseTwo
     */
    message?: string;
}

/**
 * Check if a given object implements the MainTestResponseTwo interface.
 */
export function instanceOfMainTestResponseTwo(value: object): value is MainTestResponseTwo {
    return true;
}

export function MainTestResponseTwoFromJSON(json: any): MainTestResponseTwo {
    return MainTestResponseTwoFromJSONTyped(json, false);
}

export function MainTestResponseTwoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainTestResponseTwo {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function MainTestResponseTwoToJSON(json: any): MainTestResponseTwo {
    return MainTestResponseTwoToJSONTyped(json, false);
}

export function MainTestResponseTwoToJSONTyped(value?: MainTestResponseTwo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

