/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainRepeatingQuest } from './MainRepeatingQuest';
import {
    MainRepeatingQuestFromJSON,
    MainRepeatingQuestFromJSONTyped,
    MainRepeatingQuestToJSON,
    MainRepeatingQuestToJSONTyped,
} from './MainRepeatingQuest';
import type { MainQuestsSkills } from './MainQuestsSkills';
import {
    MainQuestsSkillsFromJSON,
    MainQuestsSkillsFromJSONTyped,
    MainQuestsSkillsToJSON,
    MainQuestsSkillsToJSONTyped,
} from './MainQuestsSkills';

/**
 * 
 * @export
 * @interface MainCustomQuest
 */
export interface MainCustomQuest {
    /**
     * 
     * @type {boolean}
     * @memberof MainCustomQuest
     */
    completed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MainCustomQuest
     */
    endDate?: string;
    /**
     * 
     * @type {number}
     * @memberof MainCustomQuest
     */
    experience?: number;
    /**
     * 
     * @type {number}
     * @memberof MainCustomQuest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MainCustomQuest
     */
    name?: string;
    /**
     * 
     * @type {Array<MainQuestsSkills>}
     * @memberof MainCustomQuest
     */
    skills?: Array<MainQuestsSkills>;
    /**
     * 
     * @type {string}
     * @memberof MainCustomQuest
     */
    startDate?: string;
    /**
     * 
     * @type {Array<MainRepeatingQuest>}
     * @memberof MainCustomQuest
     */
    subQuests?: Array<MainRepeatingQuest>;
    /**
     * 
     * @type {number}
     * @memberof MainCustomQuest
     */
    subQuestsCompleted?: number;
    /**
     * 
     * @type {string}
     * @memberof MainCustomQuest
     */
    type: string;
}

/**
 * Check if a given object implements the MainCustomQuest interface.
 */
export function instanceOfMainCustomQuest(value: object): value is MainCustomQuest {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MainCustomQuestFromJSON(json: any): MainCustomQuest {
    return MainCustomQuestFromJSONTyped(json, false);
}

export function MainCustomQuestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainCustomQuest {
    if (json == null) {
        return json;
    }
    return {
        
        'completed': json['completed'] == null ? undefined : json['completed'],
        'endDate': json['end_date'] == null ? undefined : json['end_date'],
        'experience': json['experience'] == null ? undefined : json['experience'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'skills': json['skills'] == null ? undefined : ((json['skills'] as Array<any>).map(MainQuestsSkillsFromJSON)),
        'startDate': json['start_date'] == null ? undefined : json['start_date'],
        'subQuests': json['subQuests'] == null ? undefined : ((json['subQuests'] as Array<any>).map(MainRepeatingQuestFromJSON)),
        'subQuestsCompleted': json['subQuestsCompleted'] == null ? undefined : json['subQuestsCompleted'],
        'type': json['type'],
    };
}

export function MainCustomQuestToJSON(json: any): MainCustomQuest {
    return MainCustomQuestToJSONTyped(json, false);
}

export function MainCustomQuestToJSONTyped(value?: MainCustomQuest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completed': value['completed'],
        'end_date': value['endDate'],
        'experience': value['experience'],
        'id': value['id'],
        'name': value['name'],
        'skills': value['skills'] == null ? undefined : ((value['skills'] as Array<any>).map(MainQuestsSkillsToJSON)),
        'start_date': value['startDate'],
        'subQuests': value['subQuests'] == null ? undefined : ((value['subQuests'] as Array<any>).map(MainRepeatingQuestToJSON)),
        'subQuestsCompleted': value['subQuestsCompleted'],
        'type': value['type'],
    };
}

