/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainLoginBody
 */
export interface MainLoginBody {
    /**
     * 
     * @type {string}
     * @memberof MainLoginBody
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof MainLoginBody
     */
    password?: string;
}

/**
 * Check if a given object implements the MainLoginBody interface.
 */
export function instanceOfMainLoginBody(value: object): value is MainLoginBody {
    return true;
}

export function MainLoginBodyFromJSON(json: any): MainLoginBody {
    return MainLoginBodyFromJSONTyped(json, false);
}

export function MainLoginBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainLoginBody {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

export function MainLoginBodyToJSON(json: any): MainLoginBody {
    return MainLoginBodyToJSONTyped(json, false);
}

export function MainLoginBodyToJSONTyped(value?: MainLoginBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

