/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainPlayerInfoResponse
 */
export interface MainPlayerInfoResponse {
    /**
     * 
     * @type {number}
     * @memberof MainPlayerInfoResponse
     */
    experience?: number;
    /**
     * 
     * @type {number}
     * @memberof MainPlayerInfoResponse
     */
    experienceNeeded?: number;
    /**
     * 
     * @type {number}
     * @memberof MainPlayerInfoResponse
     */
    hotStreak?: number;
    /**
     * 
     * @type {number}
     * @memberof MainPlayerInfoResponse
     */
    level?: number;
    /**
     * 
     * @type {string}
     * @memberof MainPlayerInfoResponse
     */
    name?: string;
}

/**
 * Check if a given object implements the MainPlayerInfoResponse interface.
 */
export function instanceOfMainPlayerInfoResponse(value: object): value is MainPlayerInfoResponse {
    return true;
}

export function MainPlayerInfoResponseFromJSON(json: any): MainPlayerInfoResponse {
    return MainPlayerInfoResponseFromJSONTyped(json, false);
}

export function MainPlayerInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainPlayerInfoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'experience': json['experience'] == null ? undefined : json['experience'],
        'experienceNeeded': json['experienceNeeded'] == null ? undefined : json['experienceNeeded'],
        'hotStreak': json['hotStreak'] == null ? undefined : json['hotStreak'],
        'level': json['level'] == null ? undefined : json['level'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function MainPlayerInfoResponseToJSON(json: any): MainPlayerInfoResponse {
    return MainPlayerInfoResponseToJSONTyped(json, false);
}

export function MainPlayerInfoResponseToJSONTyped(value?: MainPlayerInfoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'experience': value['experience'],
        'experienceNeeded': value['experienceNeeded'],
        'hotStreak': value['hotStreak'],
        'level': value['level'],
        'name': value['name'],
    };
}

