/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainLinkedSkill
 */
export interface MainLinkedSkill {
    /**
     * 
     * @type {number}
     * @memberof MainLinkedSkill
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MainLinkedSkill
     */
    name: string;
}

/**
 * Check if a given object implements the MainLinkedSkill interface.
 */
export function instanceOfMainLinkedSkill(value: object): value is MainLinkedSkill {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MainLinkedSkillFromJSON(json: any): MainLinkedSkill {
    return MainLinkedSkillFromJSONTyped(json, false);
}

export function MainLinkedSkillFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainLinkedSkill {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
    };
}

export function MainLinkedSkillToJSON(json: any): MainLinkedSkill {
    return MainLinkedSkillToJSONTyped(json, false);
}

export function MainLinkedSkillToJSONTyped(value?: MainLinkedSkill | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

