/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DatabaseGetSkillsNotOwnedByUserRow } from './DatabaseGetSkillsNotOwnedByUserRow';
import {
    DatabaseGetSkillsNotOwnedByUserRowFromJSON,
    DatabaseGetSkillsNotOwnedByUserRowFromJSONTyped,
    DatabaseGetSkillsNotOwnedByUserRowToJSON,
    DatabaseGetSkillsNotOwnedByUserRowToJSONTyped,
} from './DatabaseGetSkillsNotOwnedByUserRow';

/**
 * 
 * @export
 * @interface MainSkillsNotOwnedResponse
 */
export interface MainSkillsNotOwnedResponse {
    /**
     * 
     * @type {Array<DatabaseGetSkillsNotOwnedByUserRow>}
     * @memberof MainSkillsNotOwnedResponse
     */
    skills?: Array<DatabaseGetSkillsNotOwnedByUserRow>;
}

/**
 * Check if a given object implements the MainSkillsNotOwnedResponse interface.
 */
export function instanceOfMainSkillsNotOwnedResponse(value: object): value is MainSkillsNotOwnedResponse {
    return true;
}

export function MainSkillsNotOwnedResponseFromJSON(json: any): MainSkillsNotOwnedResponse {
    return MainSkillsNotOwnedResponseFromJSONTyped(json, false);
}

export function MainSkillsNotOwnedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainSkillsNotOwnedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'skills': json['skills'] == null ? undefined : ((json['skills'] as Array<any>).map(DatabaseGetSkillsNotOwnedByUserRowFromJSON)),
    };
}

export function MainSkillsNotOwnedResponseToJSON(json: any): MainSkillsNotOwnedResponse {
    return MainSkillsNotOwnedResponseToJSONTyped(json, false);
}

export function MainSkillsNotOwnedResponseToJSONTyped(value?: MainSkillsNotOwnedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skills': value['skills'] == null ? undefined : ((value['skills'] as Array<any>).map(DatabaseGetSkillsNotOwnedByUserRowToJSON)),
    };
}

