/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainLinkedSkill } from './MainLinkedSkill';
import {
    MainLinkedSkillFromJSON,
    MainLinkedSkillFromJSONTyped,
    MainLinkedSkillToJSON,
    MainLinkedSkillToJSONTyped,
} from './MainLinkedSkill';

/**
 * 
 * @export
 * @interface MainSkillCreationPayload
 */
export interface MainSkillCreationPayload {
    /**
     * 
     * @type {number}
     * @memberof MainSkillCreationPayload
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MainSkillCreationPayload
     */
    isNew?: boolean;
    /**
     * 
     * @type {Array<MainLinkedSkill>}
     * @memberof MainSkillCreationPayload
     */
    linkedSkills?: Array<MainLinkedSkill>;
    /**
     * 
     * @type {string}
     * @memberof MainSkillCreationPayload
     */
    name: string;
}

/**
 * Check if a given object implements the MainSkillCreationPayload interface.
 */
export function instanceOfMainSkillCreationPayload(value: object): value is MainSkillCreationPayload {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MainSkillCreationPayloadFromJSON(json: any): MainSkillCreationPayload {
    return MainSkillCreationPayloadFromJSONTyped(json, false);
}

export function MainSkillCreationPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainSkillCreationPayload {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'isNew': json['isNew'] == null ? undefined : json['isNew'],
        'linkedSkills': json['linkedSkills'] == null ? undefined : ((json['linkedSkills'] as Array<any>).map(MainLinkedSkillFromJSON)),
        'name': json['name'],
    };
}

export function MainSkillCreationPayloadToJSON(json: any): MainSkillCreationPayload {
    return MainSkillCreationPayloadToJSONTyped(json, false);
}

export function MainSkillCreationPayloadToJSONTyped(value?: MainSkillCreationPayload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'isNew': value['isNew'],
        'linkedSkills': value['linkedSkills'] == null ? undefined : ((value['linkedSkills'] as Array<any>).map(MainLinkedSkillToJSON)),
        'name': value['name'],
    };
}

