/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainLinkedSkill } from './MainLinkedSkill';
import {
    MainLinkedSkillFromJSON,
    MainLinkedSkillFromJSONTyped,
    MainLinkedSkillToJSON,
    MainLinkedSkillToJSONTyped,
} from './MainLinkedSkill';

/**
 * 
 * @export
 * @interface MainSkill
 */
export interface MainSkill {
    /**
     * 
     * @type {number}
     * @memberof MainSkill
     */
    experience?: number;
    /**
     * 
     * @type {number}
     * @memberof MainSkill
     */
    experienceNeeded?: number;
    /**
     * 
     * @type {number}
     * @memberof MainSkill
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof MainSkill
     */
    level?: number;
    /**
     * 
     * @type {Array<MainLinkedSkill>}
     * @memberof MainSkill
     */
    linkedSkills?: Array<MainLinkedSkill>;
    /**
     * 
     * @type {string}
     * @memberof MainSkill
     */
    name: string;
}

/**
 * Check if a given object implements the MainSkill interface.
 */
export function instanceOfMainSkill(value: object): value is MainSkill {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MainSkillFromJSON(json: any): MainSkill {
    return MainSkillFromJSONTyped(json, false);
}

export function MainSkillFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainSkill {
    if (json == null) {
        return json;
    }
    return {
        
        'experience': json['experience'] == null ? undefined : json['experience'],
        'experienceNeeded': json['experienceNeeded'] == null ? undefined : json['experienceNeeded'],
        'id': json['id'] == null ? undefined : json['id'],
        'level': json['level'] == null ? undefined : json['level'],
        'linkedSkills': json['linkedSkills'] == null ? undefined : ((json['linkedSkills'] as Array<any>).map(MainLinkedSkillFromJSON)),
        'name': json['name'],
    };
}

export function MainSkillToJSON(json: any): MainSkill {
    return MainSkillToJSONTyped(json, false);
}

export function MainSkillToJSONTyped(value?: MainSkill | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'experience': value['experience'],
        'experienceNeeded': value['experienceNeeded'],
        'id': value['id'],
        'level': value['level'],
        'linkedSkills': value['linkedSkills'] == null ? undefined : ((value['linkedSkills'] as Array<any>).map(MainLinkedSkillToJSON)),
        'name': value['name'],
    };
}

