/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainProfileCreationBody
 */
export interface MainProfileCreationBody {
    /**
     * 
     * @type {string}
     * @memberof MainProfileCreationBody
     */
    bio?: string;
    /**
     * 
     * @type {string}
     * @memberof MainProfileCreationBody
     */
    dateOfBirth?: string;
    /**
     * 
     * @type {string}
     * @memberof MainProfileCreationBody
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof MainProfileCreationBody
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof MainProfileCreationBody
     */
    nickName?: string;
}

/**
 * Check if a given object implements the MainProfileCreationBody interface.
 */
export function instanceOfMainProfileCreationBody(value: object): value is MainProfileCreationBody {
    return true;
}

export function MainProfileCreationBodyFromJSON(json: any): MainProfileCreationBody {
    return MainProfileCreationBodyFromJSONTyped(json, false);
}

export function MainProfileCreationBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainProfileCreationBody {
    if (json == null) {
        return json;
    }
    return {
        
        'bio': json['bio'] == null ? undefined : json['bio'],
        'dateOfBirth': json['dateOfBirth'] == null ? undefined : json['dateOfBirth'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'nickName': json['nickName'] == null ? undefined : json['nickName'],
    };
}

export function MainProfileCreationBodyToJSON(json: any): MainProfileCreationBody {
    return MainProfileCreationBodyToJSONTyped(json, false);
}

export function MainProfileCreationBodyToJSONTyped(value?: MainProfileCreationBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bio': value['bio'],
        'dateOfBirth': value['dateOfBirth'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'nickName': value['nickName'],
    };
}

