/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainUpdateUserBody
 */
export interface MainUpdateUserBody {
    /**
     * 
     * @type {string}
     * @memberof MainUpdateUserBody
     */
    bio?: string;
    /**
     * 
     * @type {string}
     * @memberof MainUpdateUserBody
     */
    dateOfBirth?: string;
    /**
     * 
     * @type {string}
     * @memberof MainUpdateUserBody
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof MainUpdateUserBody
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof MainUpdateUserBody
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof MainUpdateUserBody
     */
    nickName?: string;
    /**
     * 
     * @type {string}
     * @memberof MainUpdateUserBody
     */
    target: string;
}

/**
 * Check if a given object implements the MainUpdateUserBody interface.
 */
export function instanceOfMainUpdateUserBody(value: object): value is MainUpdateUserBody {
    if (!('target' in value) || value['target'] === undefined) return false;
    return true;
}

export function MainUpdateUserBodyFromJSON(json: any): MainUpdateUserBody {
    return MainUpdateUserBodyFromJSONTyped(json, false);
}

export function MainUpdateUserBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainUpdateUserBody {
    if (json == null) {
        return json;
    }
    return {
        
        'bio': json['bio'] == null ? undefined : json['bio'],
        'dateOfBirth': json['dateOfBirth'] == null ? undefined : json['dateOfBirth'],
        'email': json['email'] == null ? undefined : json['email'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'nickName': json['nickName'] == null ? undefined : json['nickName'],
        'target': json['target'],
    };
}

export function MainUpdateUserBodyToJSON(json: any): MainUpdateUserBody {
    return MainUpdateUserBodyToJSONTyped(json, false);
}

export function MainUpdateUserBodyToJSONTyped(value?: MainUpdateUserBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bio': value['bio'],
        'dateOfBirth': value['dateOfBirth'],
        'email': value['email'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'nickName': value['nickName'],
        'target': value['target'],
    };
}

