/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainQuestsSkills
 */
export interface MainQuestsSkills {
    /**
     * 
     * @type {number}
     * @memberof MainQuestsSkills
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof MainQuestsSkills
     */
    name: string;
}

/**
 * Check if a given object implements the MainQuestsSkills interface.
 */
export function instanceOfMainQuestsSkills(value: object): value is MainQuestsSkills {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MainQuestsSkillsFromJSON(json: any): MainQuestsSkills {
    return MainQuestsSkillsFromJSONTyped(json, false);
}

export function MainQuestsSkillsFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainQuestsSkills {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function MainQuestsSkillsToJSON(json: any): MainQuestsSkills {
    return MainQuestsSkillsToJSONTyped(json, false);
}

export function MainQuestsSkillsToJSONTyped(value?: MainQuestsSkills | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

