/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainQuestCompletionResponse
 */
export interface MainQuestCompletionResponse {
    /**
     * 
     * @type {number}
     * @memberof MainQuestCompletionResponse
     */
    leveledUpTimes?: number;
}

/**
 * Check if a given object implements the MainQuestCompletionResponse interface.
 */
export function instanceOfMainQuestCompletionResponse(value: object): value is MainQuestCompletionResponse {
    return true;
}

export function MainQuestCompletionResponseFromJSON(json: any): MainQuestCompletionResponse {
    return MainQuestCompletionResponseFromJSONTyped(json, false);
}

export function MainQuestCompletionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainQuestCompletionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'leveledUpTimes': json['leveledUpTimes'] == null ? undefined : json['leveledUpTimes'],
    };
}

export function MainQuestCompletionResponseToJSON(json: any): MainQuestCompletionResponse {
    return MainQuestCompletionResponseToJSONTyped(json, false);
}

export function MainQuestCompletionResponseToJSONTyped(value?: MainQuestCompletionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'leveledUpTimes': value['leveledUpTimes'],
    };
}

