/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MainRepeatingQuest } from './MainRepeatingQuest';
import {
    MainRepeatingQuestFromJSON,
    MainRepeatingQuestFromJSONTyped,
    MainRepeatingQuestToJSON,
    MainRepeatingQuestToJSONTyped,
} from './MainRepeatingQuest';

/**
 * 
 * @export
 * @interface MainTypeRepeatingQuest
 */
export interface MainTypeRepeatingQuest {
    /**
     * 
     * @type {Array<MainRepeatingQuest>}
     * @memberof MainTypeRepeatingQuest
     */
    quests?: Array<MainRepeatingQuest>;
    /**
     * 
     * @type {string}
     * @memberof MainTypeRepeatingQuest
     */
    type: string;
}

/**
 * Check if a given object implements the MainTypeRepeatingQuest interface.
 */
export function instanceOfMainTypeRepeatingQuest(value: object): value is MainTypeRepeatingQuest {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function MainTypeRepeatingQuestFromJSON(json: any): MainTypeRepeatingQuest {
    return MainTypeRepeatingQuestFromJSONTyped(json, false);
}

export function MainTypeRepeatingQuestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainTypeRepeatingQuest {
    if (json == null) {
        return json;
    }
    return {
        
        'quests': json['quests'] == null ? undefined : ((json['quests'] as Array<any>).map(MainRepeatingQuestFromJSON)),
        'type': json['type'],
    };
}

export function MainTypeRepeatingQuestToJSON(json: any): MainTypeRepeatingQuest {
    return MainTypeRepeatingQuestToJSONTyped(json, false);
}

export function MainTypeRepeatingQuestToJSONTyped(value?: MainTypeRepeatingQuest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quests': value['quests'] == null ? undefined : ((value['quests'] as Array<any>).map(MainRepeatingQuestToJSON)),
        'type': value['type'],
    };
}

