/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainQuestStatsResponse
 */
export interface MainQuestStatsResponse {
    /**
     * 
     * @type {number}
     * @memberof MainQuestStatsResponse
     */
    customQuestCompleted?: number;
    /**
     * 
     * @type {number}
     * @memberof MainQuestStatsResponse
     */
    experienceGained?: number;
    /**
     * 
     * @type {number}
     * @memberof MainQuestStatsResponse
     */
    questCompleted?: number;
    /**
     * 
     * @type {number}
     * @memberof MainQuestStatsResponse
     */
    repeatingQuestCompleted?: number;
    /**
     * 
     * @type {number}
     * @memberof MainQuestStatsResponse
     */
    subQuestsCompleted?: number;
}

/**
 * Check if a given object implements the MainQuestStatsResponse interface.
 */
export function instanceOfMainQuestStatsResponse(value: object): value is MainQuestStatsResponse {
    return true;
}

export function MainQuestStatsResponseFromJSON(json: any): MainQuestStatsResponse {
    return MainQuestStatsResponseFromJSONTyped(json, false);
}

export function MainQuestStatsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainQuestStatsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'customQuestCompleted': json['customQuestCompleted'] == null ? undefined : json['customQuestCompleted'],
        'experienceGained': json['experienceGained'] == null ? undefined : json['experienceGained'],
        'questCompleted': json['questCompleted'] == null ? undefined : json['questCompleted'],
        'repeatingQuestCompleted': json['repeatingQuestCompleted'] == null ? undefined : json['repeatingQuestCompleted'],
        'subQuestsCompleted': json['subQuestsCompleted'] == null ? undefined : json['subQuestsCompleted'],
    };
}

export function MainQuestStatsResponseToJSON(json: any): MainQuestStatsResponse {
    return MainQuestStatsResponseToJSONTyped(json, false);
}

export function MainQuestStatsResponseToJSONTyped(value?: MainQuestStatsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customQuestCompleted': value['customQuestCompleted'],
        'experienceGained': value['experienceGained'],
        'questCompleted': value['questCompleted'],
        'repeatingQuestCompleted': value['repeatingQuestCompleted'],
        'subQuestsCompleted': value['subQuestsCompleted'],
    };
}

