/* tslint:disable */
/* eslint-disable */
/**
 * Your API Title
 * This is a sample API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainTestResponse
 */
export interface MainTestResponse {
    /**
     * 
     * @type {string}
     * @memberof MainTestResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the MainTestResponse interface.
 */
export function instanceOfMainTestResponse(value: object): value is MainTestResponse {
    return true;
}

export function MainTestResponseFromJSON(json: any): MainTestResponse {
    return MainTestResponseFromJSONTyped(json, false);
}

export function MainTestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainTestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function MainTestResponseToJSON(json: any): MainTestResponse {
    return MainTestResponseToJSONTyped(json, false);
}

export function MainTestResponseToJSONTyped(value?: MainTestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

