/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainSkillsResponse
 */
export interface MainSkillsResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof MainSkillsResponse
     */
    skills?: Array<string>;
}

/**
 * Check if a given object implements the MainSkillsResponse interface.
 */
export function instanceOfMainSkillsResponse(value: object): value is MainSkillsResponse {
    return true;
}

export function MainSkillsResponseFromJSON(json: any): MainSkillsResponse {
    return MainSkillsResponseFromJSONTyped(json, false);
}

export function MainSkillsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainSkillsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'skills': json['skills'] == null ? undefined : json['skills'],
    };
}

export function MainSkillsResponseToJSON(json: any): MainSkillsResponse {
    return MainSkillsResponseToJSONTyped(json, false);
}

export function MainSkillsResponseToJSONTyped(value?: MainSkillsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'skills': value['skills'],
    };
}

