/* tslint:disable */
/* eslint-disable */
/**
 * Level-Up API
 * API for Level-Up app
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainSkillExclude
 */
export interface MainSkillExclude {
    /**
     * 
     * @type {number}
     * @memberof MainSkillExclude
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof MainSkillExclude
     */
    name: string;
}

/**
 * Check if a given object implements the MainSkillExclude interface.
 */
export function instanceOfMainSkillExclude(value: object): value is MainSkillExclude {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MainSkillExcludeFromJSON(json: any): MainSkillExclude {
    return MainSkillExcludeFromJSONTyped(json, false);
}

export function MainSkillExcludeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainSkillExclude {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function MainSkillExcludeToJSON(json: any): MainSkillExclude {
    return MainSkillExcludeToJSONTyped(json, false);
}

export function MainSkillExcludeToJSONTyped(value?: MainSkillExclude | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

