// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/levelup_api/create-skill": {
            "post": {
                "description": "create skill for user",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Skills"
                ],
                "summary": "Create skill",
                "parameters": [
                    {
                        "description": "Skill creation",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.SkillCreationPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/levelup_api/createProfile": {
            "post": {
                "description": "Create the player with user's info, skills and quests",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Player"
                ],
                "summary": "Create the player",
                "parameters": [
                    {
                        "description": "Profile creation payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ProfileCreationBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.LoginResponse"
                        }
                    }
                }
            }
        },
        "/v1/levelup_api/logIn": {
            "post": {
                "description": "take the email and the password, hash the password, check for user and login",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Log In the user",
                "parameters": [
                    {
                        "description": "Login payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.LoginBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.LoginResponse"
                        }
                    }
                }
            }
        },
        "/v1/levelup_api/quests": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Quests"
                ],
                "summary": "Get all quests for the user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.QuestsReponse"
                        }
                    }
                }
            }
        },
        "/v1/levelup_api/signUp": {
            "post": {
                "description": "take the email and the password, hash the password, create the user and make cookies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Login"
                ],
                "summary": "Sign up the user",
                "parameters": [
                    {
                        "description": "SignUp payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.LoginBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.LoginResponse"
                        }
                    }
                }
            }
        },
        "/v1/levelup_api/skill/{id}/deactivate": {
            "delete": {
                "description": "deactivate the skill",
                "tags": [
                    "Skills"
                ],
                "summary": "Deactivate",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Id of the skill",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/levelup_api/skills": {
            "get": {
                "description": "get skills, limited to 200 results",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Skills"
                ],
                "summary": "Get skills from database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Get skills with the typed in prefix",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SkillsResponse"
                        }
                    }
                }
            }
        },
        "/v1/levelup_api/skills-not-user": {
            "get": {
                "description": "get skills not owned by the user, limited to 200 results",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Skills"
                ],
                "summary": "Get skills from database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Get skills with the typed in prefix and not owned by current user",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SkillsNotOwnedResponse"
                        }
                    }
                }
            }
        },
        "/v1/levelup_api/updateUser": {
            "post": {
                "description": "Update the player",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Player"
                ],
                "summary": "Update the player",
                "parameters": [
                    {
                        "description": "User update payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.UpdateUserBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/levelup_api/user/info": {
            "get": {
                "description": "Get info for the header",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Player"
                ],
                "summary": "Get player info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.PlayerInfoResponse"
                        }
                    }
                }
            }
        },
        "/v1/levelup_api/user/quest-creation": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Quests"
                ],
                "summary": "Get all quests for the user",
                "parameters": [
                    {
                        "description": "Skill creation",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.QuestCreationPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/levelup_api/user/quest/{id}/complete-subquest": {
            "post": {
                "tags": [
                    "Quests"
                ],
                "summary": "Complete a sub-quest",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the quest",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/levelup_api/user/quest/{id}/delete-subquest": {
            "delete": {
                "tags": [
                    "Quests"
                ],
                "summary": "Delete a sub-quest",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the quest",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/v1/levelup_api/user/skills": {
            "get": {
                "description": "get user's skills",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Skills"
                ],
                "summary": "Get user's skills from database",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.UsersSkillsResponse"
                        }
                    }
                }
            }
        },
        "/v1/levelup_api/user/skills_exclude": {
            "get": {
                "description": "get user's skills",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Skills"
                ],
                "summary": "Get user's skills from database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Get skills with the typed in prefix",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "csv",
                        "description": "Exclude skills",
                        "name": "exclude_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Exclude given skill",
                        "name": "excludeName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SkillsExcludeResponse"
                        }
                    }
                }
            }
        },
        "/v1/levelup_api/userProfile": {
            "get": {
                "description": "Get everything about the player",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Player"
                ],
                "summary": "Get the player",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.UserResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "database.GetSkillsByNameRow": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "database.GetSkillsNotOwnedByUserRow": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "main.CustomQuest": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "completed": {
                    "type": "boolean"
                },
                "end_date": {
                    "type": "string"
                },
                "experience": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.QuestsSkills"
                    }
                },
                "start_date": {
                    "type": "string"
                },
                "subQuests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.RepeatingQuest"
                    }
                },
                "subQuestsCompleted": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "main.LinkedSkill": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "main.LoginBody": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "main.LoginResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "redirect": {
                    "type": "string"
                }
            }
        },
        "main.PlayerInfoResponse": {
            "type": "object",
            "properties": {
                "experience": {
                    "type": "integer"
                },
                "experienceNeeded": {
                    "type": "integer"
                },
                "hotStreak": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "main.ProfileCreationBody": {
            "type": "object",
            "properties": {
                "bio": {
                    "type": "string"
                },
                "dateOfBirth": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "nickName": {
                    "type": "string"
                },
                "quests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.QuestsCreation"
                    }
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.SkillsCreation"
                    }
                }
            }
        },
        "main.ProfileResponse": {
            "type": "object",
            "required": [
                "email",
                "firstName",
                "lastName",
                "nickName"
            ],
            "properties": {
                "dateOfBirth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "nickName": {
                    "type": "string"
                }
            }
        },
        "main.QuestCreationPayload": {
            "type": "object",
            "properties": {
                "endDate": {
                    "type": "string"
                },
                "experience": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.SkillCreationPayload"
                    }
                },
                "startDate": {
                    "type": "string"
                },
                "subQuests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.RepeatingQuest"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "main.QuestsCreation": {
            "type": "object",
            "properties": {
                "experience": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "main.QuestsReponse": {
            "type": "object",
            "properties": {
                "customQuests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.CustomQuest"
                    }
                },
                "repeatingQuests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.TypeRepeatingQuest"
                    }
                }
            }
        },
        "main.QuestsSkills": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "main.RepeatingQuest": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "completed": {
                    "type": "boolean"
                },
                "experience": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.QuestsSkills"
                    }
                },
                "subQuests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.RepeatingQuest"
                    }
                },
                "subQuestsCompleted": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "main.Skill": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "experience": {
                    "type": "integer"
                },
                "experienceNeeded": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                },
                "linkedSkills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.LinkedSkill"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "main.SkillCreationPayload": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "isNew": {
                    "type": "boolean"
                },
                "linkedSkills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.LinkedSkill"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "main.SkillExclude": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "linkedSkills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.LinkedSkill"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "main.SkillsCreation": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "main.SkillsExcludeResponse": {
            "type": "object",
            "properties": {
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.SkillExclude"
                    }
                }
            }
        },
        "main.SkillsNotOwnedResponse": {
            "type": "object",
            "properties": {
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.GetSkillsNotOwnedByUserRow"
                    }
                }
            }
        },
        "main.SkillsResponse": {
            "type": "object",
            "properties": {
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/database.GetSkillsByNameRow"
                    }
                }
            }
        },
        "main.TypeRepeatingQuest": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "quests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.RepeatingQuest"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "main.UpdateUserBody": {
            "type": "object",
            "required": [
                "target"
            ],
            "properties": {
                "bio": {
                    "type": "string"
                },
                "dateOfBirth": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "nickName": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "main.UserResponse": {
            "type": "object",
            "required": [
                "profile"
            ],
            "properties": {
                "bio": {
                    "type": "string"
                },
                "highestLeveledSkill": {
                    "type": "string"
                },
                "mostRecentLeveledSkill": {
                    "type": "string"
                },
                "profile": {
                    "$ref": "#/definitions/main.ProfileResponse"
                }
            }
        },
        "main.UsersSkillsResponse": {
            "type": "object",
            "properties": {
                "skills": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Skill"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Level-Up API",
	Description:      "API for Level-Up app",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
