definitions:
  database.GetSkillsByNameRow:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  main.LoginBody:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  main.LoginResponse:
    properties:
      code:
        type: string
      redirect:
        type: string
    type: object
  main.SkillsResponse:
    properties:
      skills:
        items:
          $ref: '#/definitions/database.GetSkillsByNameRow'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for Level-Up app
  title: Level-Up API
  version: "0.1"
paths:
  /v1/levelup_api/logIn:
    post:
      consumes:
      - application/json
      description: take the email and the password, hash the password, check for user
        and login
      parameters:
      - description: Login payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.LoginBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.LoginResponse'
      summary: Log In the user
      tags:
      - Login
  /v1/levelup_api/signUp:
    post:
      consumes:
      - application/json
      description: take the email and the password, hash the password, create the
        user and make cookies
      parameters:
      - description: SignUp payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.LoginBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.LoginResponse'
      summary: Sign up the user
      tags:
      - Login
  /v1/levelup_api/skills:
    get:
      description: get skills, limited to 200 results
      parameters:
      - description: Get skills with the typed in prefix
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.SkillsResponse'
      summary: Get skills from database
      tags:
      - Skills
swagger: "2.0"
