definitions:
  main.SkillsResponse:
    properties:
      skills:
        items:
          type: string
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for Level-Up app
  title: Level-Up API
  version: "0.1"
paths:
  /v1/levelup_api/skills:
    get:
      description: get skills, limited to 200 results
      parameters:
      - description: Get skills with the typed in prefix
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.SkillsResponse'
      summary: Get skills from database
      tags:
      - Skills
swagger: "2.0"
