definitions:
  database.GetSkillsByNameRow:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  main.LoginBody:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  main.LoginResponse:
    properties:
      code:
        type: string
      redirect:
        type: string
    type: object
  main.ProfileCreationBody:
    properties:
      bio:
        type: string
      dateOfBirth:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      nickName:
        type: string
    type: object
  main.ProfileResponse:
    properties:
      dateOfBirth:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      nickName:
        type: string
    required:
    - email
    - firstName
    - lastName
    - nickName
    type: object
  main.SkillsResponse:
    properties:
      skills:
        items:
          $ref: '#/definitions/database.GetSkillsByNameRow'
        type: array
    type: object
  main.UpdateUserBody:
    properties:
      bio:
        type: string
      dateOfBirth:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      nickName:
        type: string
      target:
        type: string
    required:
    - target
    type: object
  main.UserResponse:
    properties:
      bio:
        type: string
      profile:
        $ref: '#/definitions/main.ProfileResponse'
    required:
    - profile
    type: object
host: localhost:8080
info:
  contact: {}
  description: API for Level-Up app
  title: Level-Up API
  version: "0.1"
paths:
  /v1/levelup_api/createProfile:
    post:
      consumes:
      - application/json
      description: Create the player with user's info, skills and quests
      parameters:
      - description: Profile creation payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.ProfileCreationBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.LoginResponse'
      summary: Create the player
      tags:
      - Player
  /v1/levelup_api/logIn:
    post:
      consumes:
      - application/json
      description: take the email and the password, hash the password, check for user
        and login
      parameters:
      - description: Login payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.LoginBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.LoginResponse'
      summary: Log In the user
      tags:
      - Login
  /v1/levelup_api/signUp:
    post:
      consumes:
      - application/json
      description: take the email and the password, hash the password, create the
        user and make cookies
      parameters:
      - description: SignUp payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.LoginBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.LoginResponse'
      summary: Sign up the user
      tags:
      - Login
  /v1/levelup_api/skills:
    get:
      description: get skills, limited to 200 results
      parameters:
      - description: Get skills with the typed in prefix
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.SkillsResponse'
      summary: Get skills from database
      tags:
      - Skills
  /v1/levelup_api/updateUser:
    post:
      consumes:
      - application/json
      description: Update the player
      parameters:
      - description: User update payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.UpdateUserBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update the player
      tags:
      - Player
  /v1/levelup_api/userProfile:
    get:
      description: Get everything about the player
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.UserResponse'
      summary: Get the player
      tags:
      - Player
swagger: "2.0"
